apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.quilr.appname }}
  namespace: {{ .Values.namespace | default "quilr" }}  # Use namespace from values.yaml
  labels:
    app: {{ .Values.quilr.appname }}
spec:
  replicas: {{ .Values.hpa.minReplicas }}  # This will be managed by the HPA
  selector:
    matchLabels:
      app: {{ .Values.quilr.appname }}
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "{{ .Values.vault.addr }}"
        vault.security.banzaicloud.io/vault-role: "{{ .Values.vault.role }}"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/vault-agent: "false"
        vault.security.banzaicloud.io/vault-path: "{{ .Values.vault.path }}"
      name: {{ .Values.quilr.appname }}
      labels:
        app: {{ .Values.quilr.appname }}
    spec:
      initContainers:
        - name: wait-for-vault
          image: quilrdev.azurecr.io/bitnamilegacy/quilr-tp:curl-8.5.0
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              echo "Waiting for Vault at {{ .Values.vault.addr }}..."
              until curl -k -sSf {{ .Values.vault.addr }}/v1/sys/health; do
                echo "Vault not ready, retrying in 5s..."
                sleep 5
              done
              echo "Vault is ready!"
      containers:
        - name: {{ .Values.quilr.appname }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 90
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 90
            periodSeconds: 5
            failureThreshold: 5
          env:
            - name: AZURE_API_VERSION
              value: vault:secret/data/quilr-common-config-vault#AZURE_API_VERSION
            - name: AZURE_BASE_URL
              value: vault:secret/data/quilr-common-config-vault#AZURE_BASE_URL
            - name: AZURE_API_KEY
              value: vault:secret/data/quilr-common-config-vault#AZURE_API_KEY
            - name: AZURE_LLM_NAME
              value: vault:secret/data/quilr-common-config-vault#AZURE_LLM_NAME
            - name: ES_PASSWORD
              value: vault:secret/data/quilr-common-config-vault#ES_PASSWORD 
            - name: NEO4J.USER_NAME
              value: vault:secret/data/quilr-common-config-vault#NEO4J.USER_NAME
            - name: NEO4J.DATABASE
              value: vault:secret/data/quilr-common-config-vault#NEO4J.DATABASE
            - name: NEO4J.URIS
              value: vault:secret/data/quilr-common-config-vault#NEO4J.URIS
            - name: NEO4J.USER_PASSWORD
              value: vault:secret/data/quilr-common-config-vault#NEO4J.USER_PASSWORD
            - name: FILE_LOCATION
              value: "/quilr-inferencing-models-ca.crt/es_server.pem"
          envFrom:
            #- configMapRef:
           #     name: quilr-common-config
            - configMapRef:
                name: dlp-common-config
            - secretRef:
                name: {{ .Values.secretRef.name }}
            - configMapRef:
                name: {{ .Values.quilr.appname }}-configmap
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          volumeMounts:
            - name: es-db-certs-volume
              mountPath: /{{ .Values.quilr.appname }}-ca.crt
              readOnly: true
      volumes:
        - name: es-db-certs-volume
          secret:
            secretName: {{ .Values.secrets.esdbcert}}
