namespace: quilr
quilr:
  appname: quilr-inferencing-models
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: quilrdev.azurecr.io/quilr-inferencing-models
  tag: latest_prod
  pullPolicy: Always
resources:
  requests:
    memory: "1024Mi"
    cpu: "125m"
  limits:
    memory: "2048Mi"
    cpu: "1000m"
secretRef:
  name: auth-key-public
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
service:
  name: quilr-inferencing-models
  type: ClusterIP
  port: 8090
  targetPort: 8090
# Additional fields
secrets:
  esdbcert: quilr-es-db-certs-prod-saas
