## values.yaml
#****************** for deployment.yaml ******************#

namespace: quilr
quilr:
  appname: extension-api-service
### for hpa.yaml

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: 975050335771.dkr.ecr.us-east-1.amazonaws.com/main/extension-api-service
  tag: latest
  pullPolicy: Always
configMap:
  RELAY_CONFIG_DIR: "/extension-api-service/static/relays"
  LOOKUP_CONFIG_DIR: "/extension-api-service/static/lookups"
  RULE_CONFIG_DIR: "/extension-api-service/static/rule_configurations"
  BLOB_URL: "https://staticcontent1.blob.core.windows.net/onboarding/knowYourOrg.json"
  MDM_CONFIG_DIR: "/extension-api-service/static/mdm_configurations"
  GRAPH_NAME: 'neo4j'
  STORAGE_ICON_CONTAINER_NAME: 'icons'
  USER_DETAILS_TTL: 900
  APP_DETAILS_TTL: 900
  ORG_DOMAIN_TTL: 900
secretRef:
  name: auth-key-public
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
secretName: azure-secret
azurefileshare:
  name: extension-api-service
commonFileshare:
  name: quilr-data-upload
  ##################service-name: classification-config-service ####################################################
#****************** for service.yaml ******************#
service:
  name: extension-api-service
  type: ClusterIP
  port: 8097
  targetPort: 8097
#*******************************************************#

