namespace: quilr

configMap:
  KAFKA_BROKER_HOST: "b-1.quilrmsk.52zlhi.c22.kafka.us-east-1.amazonaws.com,b-2.quilrmsk.52zlhi.c22.kafka.us-east-1.amazonaws.com"
  KAFKA_BROKER: "b-1.quilrmsk.52zlhi.c22.kafka.us-east-1.amazonaws.com:9092,b-2.quilrmsk.52zlhi.c22.kafka.us-east-1.amazonaws.com:9092"
  KAFKA_BOOTSTRAP_SERVER: "b-1.quilrmsk.52zlhi.c22.kafka.us-east-1.amazonaws.com:9092,b-2.quilrmsk.52zlhi.c22.kafka.us-east-1.amazonaws.com:9092"
  KAFKA_BROKER_PORT: "9092"
  PG_PORT: "4583"
  PG_DB: "quilr"
  PG_DATABASE: "quilr"
  REDIS_HOST: "master.quilr-redis.4sslx1.use1.cache.amazonaws.com"
  redis.host: "master.quilr-redis.4sslx1.use1.cache.amazonaws.com"
  redis.port: "9200"
  REDIS_PORT: "9200"
  REDIS_DB: "0"
  VAULT_HOST: "vault.quilr.svc.cluster.local"
  VAULT_BASE_URL: "https://vault.quilr.svc.cluster.local:8200"
  VAULT_ADDR: "https://vault.quilr.svc.cluster.local:8200"
  VAULT_PORT: "8200"
  VAULT_PROTOCOL: "https"
  CONTENT_SERVER_URL: "http://content-server-transformations:8001"
  SEARCH_API_ENDPOINT: "http://search-service:8002"
  SEARCH_SERVICE_HOST: "search-service"
  SEARCH_SERVICE_PORT: "8002"
  SEARCH_API_HOST: "search-service"
  SEARCH_API_PORT: "8002"
  SEARCH_SERVICE_URL: "http://search-service:8002/api/v1/search/"
  SEARCH_SERVICE: "http://search-service:8002/api/v1/search/"
  LAMBDA_SERVICE_HOST: "content-lambda-service"
  LAMBDA_SERVICE_PORT: "9001"
  TRACKING_SERVICE_HOST: "content-tracking-service"
  TRACKING_SERVICE_PORT: "9037"
  TRACKING_API_HOST: "content-tracking-service"
  TRACKING_API_PORT: "9037"
  INSTANCE_MANAGER_SERVICE_HOST: "instance-manager-service"
  INSTANCE_MANAGER_SERVICE_PORT: "8082"
  CLASSIFICATION_REPOSITORY_URL: "http://classification-config-service:8808/get/content"
  AUTH_API_HOST: "quilr-auth-ts"
  AUTH_API_PORT: "5555"
  AUTH_API_CLIENT: "quilr-auth-ts"
  AUTH_API_PORT: "5555"
  QUILR_AUTH: "http://quilr-auth-ts:5555"
  PLAYBOOK_API_HOST: "quilr-playbook-service"
  PLAYBOOK_API_PORT: "9051"
  MAIL_HOST: "smtp.office365.com"
  MAIL_PORT: "587"
  MAIL_PROTOCOL: "smtp"
  EMAIL_API_HOST: "system-email-service"
  EMAIL_API_PORT: "9022"
  EMAIL_SERVICE: "http://system-email-service:9022/api/v1/email/send"
  TEMPLATE_API_HOST: "templating-engine"
  TEMPLATE_API_PORT: "9058"
  CONTENT_REPO_URI: "http://content-repository-service:8801"
  REPOSITORY_API_HOST: "content-repository-service"
  REPOSITORY_API_PORT: "8801"
  RESPONSE_GATEWAY_HOST: "user-response-action-service"
  RESPONSE_GATEWAY_PORT: "9085"
  SELF_HOST: "quilr-playbook-service"  
  SELF_PORT: "9051"
  LLM_SERVICE_HOST: "copilot-workflow-executor"
  LLM_SERVICE_PORT: "7054"
  DATA_CONFIG_API_HOST: "data-config-api"
  DATA_CONFIG_API_PORT: "8000"
  SCHEDULER_API_HOST: "content-scheduler-service"
  SCHEDULER_API_PORT: "8802"
  SCHEDULER_SERVICE_HOST: "content-scheduler-service"
  SCHEDULER_SERVICE_PORT:  "8802"
  QUILR_DATA_HARVESTER_SERVICE: "http://user-data-harvester:3005"
  QUILR_BROWSER_EXTENSION_SERVICE: "http://browser-extension-service:8085"
  APP_SYNC_API_ENDPOINT: "http://app-sync-client-service:8081"
  RAG_DOMAIN: "http://quilr-inferencing-models:8090"
  APP_SYNC_SERVICE_PORT: "8081"
  APP_SYNC_SERVICE_HOST: "app-sync-client-service"
# Newly added for 2-way agent and sscheduler service  
  QUILR_SEARCH_SERVICE: "http://search-service:8002"
  QUILR_SCHEDULER_SERVICE: "http://quilr-scheduler-service:8000"
  QUILR_USER_RESPONSE_SERVICE: "http://user-response-service:9085"
  QUILR_AGENT_SERVICE: "http://quilr-agent-service:8000"
  QUILR_PLAYBOOK_SERVICE: "http://quilr-playbook-service:9051"
  CLASSIFIER_DOMAIN: "https://dlpone.quilr.ai/dlp"
  COLLECTOR_DOMAIN: "http://dlp-data-collector:8093"
  DEFAULT_KNOWLEDGE_DB: "neo4j"
  Neo4J_LLAMA_ENDPOINT: "http://quilr-inferencing-models:8090/rag/twoway"
  OPENAI_MINI_BASE_URL: "https://quilr-openai.openai.azure.com"
  OPENAI_EMBEDDING_BASE_URL: "https://quilr-openai-latest.openai.azure.com"
  OPENAI_LATEST_BASE_URL: "https://quilr-41.openai.azure.com"
  SLACK_INTEGRATION_URL: "https://quilrpoc.axisb.com/bff/auth/auth/integration-admin-landing/slack"
  AGENT_SERVICE_HOST: "quilr-agent-service"
  CLASSIFICATION_CONFIG_API_HOST: "classification-config-service"
  AGENT_SERVICE_PORT: "8000"
  DLP_DATA_DEFINITION_URL: "https://quilrpoc.axisb.com/bff/dlp-data-definition"
  OOB_DDs: 'PII,PFI,PHI,SECRET'
  AI_SERVICE_URL: 'http://quilr-ai-services:8050'
  # new for quilr-memory-mcp server
  ELASTIC_URL: "https://quilr-db-elasticsearch:9200"
  # OPENAI_LATEST_API_KEY: "88EudYi4OjOB1c6KeCl1VfEG1cNaNx9YevfMtC7rQ88Lo0ZMHFSdJQQJ99BDACHYHv6XJ3w3AAAAACOGwC3C"
  # OPENAI_MINI_API_KEY: "ae11be8cf0334f8e80b347dc7018c805"
  # OPENAI_EMBEDDING_API_KEY: "05f856e9c2ec4793926d6d3928cab692"
  DLP_UPDATE_URL: "https://dlpone.quilr.ai/dlp/tenant_config"
  QUILR_MCP_MEMORY_SERVICE: "http://quilr-memory-mcp:8008"
  AZURE_BLOB_URL: "https://staticcontent1.blob.core.windows.net/quilrstatic/"
  # Added for Quilr-EAM-service
  OIDCIssuer: https://quilrpoc.axisb.com/bff/quilr-eam-service
  OIDC_MICROSOFT_CLIENT_ID: "f326db16-07b5-4705-8f16-fd91ddd949f7"
  AZURE_BLOB_URL: "https://staticcontent1.blob.core.windows.net/quilrstatic/"
  # new changes DEVOPS-293
  AI_SERVICE_URL: 'http://quilr-ai-services:8050'
  ELASTIC_URL: "https://quilr-db-elasticsearch:9200"
  DLP_UPDATE_URL: "https://dlpone.quilr.ai/dlp/tenant_config"
  QUILR_MCP_MEMORY_SERVICE: "http://quilr-memory-mcp:8008"
  OIDCIssuer: https://quilrpoc.axisb.com/bff/quilr-eam-service
  OIDC_MICROSOFT_CLIENT_ID: "f326db16-07b5-4705-8f16-fd91ddd949f7"
  CONTENT_KNOWLEDGE_SERVICE_HOST: "content-knowledgebase-service"
  CONTENT_KNOWLEDGE_SERVICE_PORT: "8806"
  #DEVOPS-302 - Display Ext version in UI
  EXTENATION_BASE_URL: "https://quilr-extensions.quilr.ai"
  EXTENAION_VERSION_FILE: "/lastupdate.json"
  DLP_MAIN_SERVER_URL: "https://dlpone.quilr.ai"
  STORAGE_CONTAINER_NAME: 'logos'
  STORAGE_ICON_CONTAINER_NAME: 'icons'
  BASE_URL: 'quilrpoc.axisb.com'
  DEPLOYMENT_TYPE: 'SAAS'
  # MS Teams integration
  MicrosoftBotAppId: "40003e8d-c4d3-4a91-b92a-d47e557fda66"
  MicrosoftBotAppPassword: "M3g8Q~OXMomhc1eq7jf6dtPYxi7g7WUlm4TdzaeY"
  quilr_base_url: "https://guardrails.quilr.ai/openai_compatible/"
  # AI Asset discovery for Azure
  DW_HOST: "http://10.71.14.215"
  DW_PORT: "8123"
  DW_NAME: 'clickhouse'
  DW_USER: 'default'
  # DLP PROMPT CSTEGORY URL SEPERATION
  DLP_RESPONSE_URL: "https://dlppreprod.quilr.ai/dlp/dlpoob/detect"
  PROMPT_CATEGORIZATION_URL: "https://dlppreprod.quilr.ai/categorize/prompt_category" 
  SIEM_SERVICE_HOST: "quilr-siem-service"
  SIEM_SERVICE_PORT: "8000"
  QUERY_BUILDER_SERVICE_HOST: "quilr-query-builder"
  QUERY_BUILDER_SERVICE_PORT: "8052"
  EXTENSION_API_SERICE_HOST: "extension-api-service"
  EXTENSION_API_SERICE_PORT: "8097" 
  TRANSFORMATION_SERVICE_HOST: "content-server-transformations"
  TRANSFORMATION_SERVICE_PORT: "8001"
  PG_AUTH_DB: "quilr_auth"
