namespace: quilr
quilr:
  appname: dlp-model-trainer
### for hpa.yaml
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
image:
  repository: 975050335771.dkr.ecr.ap-south-1.amazonaws.com/quilr-preprod/dlp-model-trainer
  tag: latest
  pullPolicy: Always
service:
  name: dlp-model-trainer
  type: ClusterIP
  port: 8000
  targetPort: 8000
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
secretRef:
  name: auth-key-public
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
