apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
    #nginx.ingress.kubernetes.io/server-alias:  <pvtip/lb>
  name: quilr-ingress
  namespace: quilr
spec:
  ingressClassName: alb
  rules:
  - host: quilr.axisbank.com
    http:
      paths:
      - backend:
          service:
            name: quilr-bff
            port:
              number: 80
        path: /bff/(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: quilr-dlp-server
            port:
              number: 8000
        path: /dlp/(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - quilr.axisbank.com
    secretName: quilr-tls-secret-axis-bank