apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    # cert-manager.io/issuer: letsencrypt-prod
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/use-regex: "true"
  name: quilr-ingress-beoauth
  namespace: quilr
spec:
  ingressClassName: alb
  rules:
  - host: quilr.axisbank.com
    http:
      paths:
      - backend:
          service:
            name: quilr-be-oauth
            port:
              number: 8080
        path: /ext-beoauth(/|$)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - quilr.axisbank.com
    secretName: quilr-tls-secret-axis-bank
