apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    # cert-manager.io/issuer: "letsencrypt-prod"
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/service-upstream: "true"
    #nginx.ingress.kubernetes.io/server-alias:  <pvtip/lb>
  name: quilr-ingress-web
  namespace: quilr
spec:
  ingressClassName: alb
  rules:
  - host: quilr.axisbank.com
    http:
      paths:
      - backend:
          service:
            name: quilr-static-content
            port:
              number: 8080
        path: /quilrstatic/
        pathType: Prefix
      - backend:
          service:
            name: quilr-web
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - quilr.axisbank.com
    secretName: quilr-tls-secret-axis-bank
