apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
#    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/server-alias:  10.122.208.4
  name: quilr-ingress
  namespace: quilr
spec:
  ingressClassName: nginx
  rules:
  - host: quilr.axisbank.com
    http:
      paths:
      - backend:
          service:
            name: quilr-bff
            port:
              number: 80
        path: /bff/(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: quilr-dlp-server
            port:
              number: 8000
        path: /dlp/(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - quilr.axisbank.com
    secretName: quilr-tls-secret-iifl
