apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.quilr.appname }}-configmap
  namespace: {{ .Values.namespace | default "default" }}
data:
  APP_STAGE: "{{ .Values.configMap.APP_STAGE }}"
  DEBUG: "{{ .Values.configMap.DEBUG }}"
  LOG_LEVEL: "{{ .Values.configMap.LOG_LEVEL }}"
  PORT: "{{ .Values.configMap.PORT }}"
  AZURE_OPENAI_ENDPOINT: "{{ .Values.configMap.AZURE_OPENAI_ENDPOINT }}"
  AZURE_OPENAI_DEPLOYMENT_NAME: "{{ .Values.configMap.AZURE_OPENAI_DEPLOYMENT_NAME }}"
  AZURE_OPENAI_API_VERSION: "{{ .Values.configMap.AZURE_OPENAI_API_VERSION }}"
  AZURE_OPENAI_MODEL_NAME: "{{ .Values.configMap.AZURE_OPENAI_MODEL_NAME }}"
  GROQ_OPENAI_MODEL_NAME: "{{ .Values.configMap.GROQ_OPENAI_MODEL_NAME }}"
