# Namespace and application name
namespace: quilr
quilr:
  appname: quilr-azurecloud-fabric

# CronJob-specific values
cronjob:
  schedule: "0 */6 * * *"
  concurrencyPolicy: "Forbid"
  ttlSecondsAfterFinished: "300"
  activeDeadlineSeconds: "86400"
  backoffLimit: "2"

# Vault configuration for annotations and passthrough
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  vault-env-passthrough: "VAULT_ADDR,VAULT_TOKEN"
  role: "default"
  path: "kubernetes"

# Container image configuration
image:
  repository: 975050335771.dkr.ecr.us-east-1.amazonaws.com/main/quilr-azurecloud-fabric
  tag: latest
  pullPolicy: Always

configMap:
  logging_level: "INFO"
  FetchInterval: "300"
  IntegrationId: "6c24a79d-0666-4930-baff-200a89a803db"
