## No specific configmap.yaml for the service
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Values.quilr.appname }}-configmap
  namespace: {{ .Values.namespace | default "default" }}  # Use namespace from values.yaml
data:
 # QUILR_SERVER_URL: "{{ .Values.configMap.QUILR_SERVER_URL }}"
  ADMIN_AUTH_TOKEN: "{{ .Values.configMap.ADMIN_AUTH_TOKEN }}"
  LLM_PROXY_DATA_DIR: "{{ .Values.configMap.LLM_PROXY_DATA_DIR }}"
  GUARD_URL: "{{ .Values.configMap.GUARD_URL }}"
  STAGE1_URL: "{{ .Values.configMap.STAGE1_URL }}"
  STAGE2_URL: "{{ .Values.configMap.STAGE2_URL }}"
  EDM_URL: "{{ .Values.configMap.EDM_URL }}"