namespace: quilr
quilr:
  appname: quilr-playbook-service
configMap:
  CONTROL_TEMPLATES_DIR: "/quilr-playbook-service/static/execution_controls"
  TEMPLATES_DIR: '/quilr-playbook-service/static/templates/message'
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: 975050335771.dkr.ecr.ap-south-1.amazonaws.com/main/quilr-playbook-service
  tag: latest
  pullPolicy: Always
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
secretRef:
  name: auth-key-public
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
service:
  name: quilr-playbook-service
  type: ClusterIP
  port: 9051
  targetPort: 9051
# Additional fields
secretName: azure-secret
azurefileshare:
  name: quilr-playbook-service
