namespace: quilr
quilr:
  appname: content-repository-service
configMap:
  STATIC_DIR_LOCATION: "/content-repository-service"
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: quilrdev.azurecr.io/content-repository-service
  tag: latest_prod
  pullPolicy: Always
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "2048Mi"
    cpu: "1000m"
secretRef:
  name: auth-key-public
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
service:
  name: content-repository-service
  type: ClusterIP
  port: 8801
  targetPort: 8801
# Additional fields
secretName: azure-secret
azurefileshare:
  name: secopsquilrstgfileshare