## values.yaml
#****************** for deployment.yaml ******************#
namespace: quilr
quilr:
  appname: data-block-receiver-service
### for hpa.yaml
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: 975050335771.dkr.ecr.ap-south-1.amazonaws.com/quilr-preprod/data-block-receiver-service
  tag: latest
  pullPolicy: Always
secretRef:
  name: auth-key-public
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
secretName: azure-secret
azurefileshare:
  name: truststore-cloud-saas-env
  #########service-name: data-block-sender-service ############
secrets:
  vaulttrustrore: quilr-vault-trustore
  #########service-name: data-block-sender-service ############
#****************** for service.yaml ******************#
service:
  name: data-block-receiver-service
  type: ClusterIP
  port: 9033
  targetPort: 9033
#****************** for configmap.yaml - particularly service related ******************#
#configMap:
# VAULT_CERT_FILE: 'file:/data-block-receiver-service-truststore/truststore.jks'
#commented configmap.yaml which is service specific
