## values.yaml
#****************** for deployment.yaml ******************#
namespace: quilr
quilr:
  appname: quilr-findingresolution-service
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: 975050335771.dkr.ecr.ap-south-1.amazonaws.com/quilr-preprod/quilr-findingresolution-service
  tag: latest
  pullPolicy: Always
configMap:
  RESOLUTION_MCP_TOOLS: "/app/mcp_server.py"
secretRef:
  name: auth-key-public
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
#****************** for service.yaml ******************#
service:
  name: quilr-findingresolution-service
  type: ClusterIP
  port: 8099
  targetPort: 8099
#*******************************************************#
