apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.quilr.appname }}-configmap
  namespace: {{ .Values.namespace | default "default" }}
data:
  ENV: "{{ .Values.configMap.ENV }}"
  DEBUG: "{{ .Values.configMap.DEBUG }}"
  AGGREGATOR_URL: "{{ .Values.configMap.AGGREGATOR_URL }}"
  BATCH_SIZE: "{{ .Values.configMap.BATCH_SIZE }}"
  CHUNK_SIZE: "{{ .Values.configMap.CHUNK_SIZE }}"
  ABS_OUTPUT_FILE_PATH: "/{{ .Values.quilr.storagename }}/prompt_results.json"
