apiVersion: v1
kind: ConfigMap
metadata:
  name: dlp-common-config
  namespace: {{ .Values.namespace | default "quilr" }}  # Use namespace from values.yaml
data:
  #SERVER_PORT: "{{ .Values.configMap.SERVER_PORT }}"
  KAFKA_BROKERS: "{{ .Values.configMap.KAFKA_BROKERS }}"
  REDIS_PORT: "{{ .Values.configMap.REDIS_PORT }}"
  REDIS_HOST: "{{ .Values.configMap.REDIS_HOST }}"
  REDIS_TIMEOUT: "{{ .Values.configMap.REDIS_TIMEOUT }}"
  ELASTIC_URL: "{{ .Values.configMap.ELASTIC_URL }}"
  ELASTIC_USERNAME: "{{ .Values.configMap.ELASTIC_USERNAME }}"
  ELASTIC_CONNECTION_TIMEOUT: "{{ .Values.configMap.ELASTIC_CONNECTION_TIMEOUT }}"
  ELASTIC_READ_TIMEOUT: "{{ .Values.configMap.ELASTIC_READ_TIMEOUT }}"
  ELASTIC_REST_ENABLED: "{{ .Values.configMap.ELASTIC_REST_ENABLED }}"
  ELASTIC_REPOSITORIES_ENABLED: "{{ .Values.configMap.ELASTIC_REPOSITORIES_ENABLED }}"
  ELASTIC_CONNECTION_POOL: "{{ .Values.configMap.ELASTIC_CONNECTION_POOL }}"
  KAFKA_CONSUMER_DEDUPLICATION_GROUPID: "{{ .Values.configMap.KAFKA_CONSUMER_DEDUPLICATION_GROUPID }}"
  KAFKA_OFFSET: "{{ .Values.configMap.KAFKA_OFFSET }}"
  KAFKA_KEY_DESERIALIZER: "{{ .Values.configMap.KAFKA_KEY_DESERIALIZER }}"
  KAFKA_VALUE_DESERIALIZER: "{{ .Values.configMap.KAFKA_VALUE_DESERIALIZER }}"
  KAFKA_CONFIG_DEDUPLICATION_CONSUMER_TOPIC: "{{ .Values.configMap.KAFKA_CONFIG_DEDUPLICATION_CONSUMER_TOPIC }}"
  KAFKA_CONFIG_CLASSIFICATION_PRODUCER_TOPIC: "{{ .Values.configMap.KAFKA_CONFIG_CLASSIFICATION_PRODUCER_TOPIC }}"
  KAFKA_CONFIG_DELETION_CONSUMER_GROUPID: "{{ .Values.configMap.KAFKA_CONFIG_DELETION_CONSUMER_GROUPID }}"
  KAFKA_CONFIG_INDEXER_CONSUMER_GROUPID: "{{ .Values.configMap.KAFKA_CONFIG_INDEXER_CONSUMER_GROUPID }}"
  KAFKA_CONFIG_INDEXER_CONSUMER_TOPIC: "{{ .Values.configMap.KAFKA_CONFIG_INDEXER_CONSUMER_TOPIC }}"
  KAFKA_CONFIG_DEDUPLICATION_PRODUCER_TOPIC: "{{ .Values.configMap.KAFKA_CONFIG_DEDUPLICATION_PRODUCER_TOPIC }}"
  FILES_DOWNLOAD_LOCATION: "{{ .Values.configMap.FILES_DOWNLOAD_LOCATION }}"
  DLP_DEDUPLICATION_SERVICE_URL: "{{ .Values.configMap.DLP_DEDUPLICATION_SERVICE_URL }}"
  ELASTIC_DLP_METRICS_REPLICAS: "{{ .Values.configMap.ELASTIC_DLP_METRICS_REPLICAS }}" 
  ELASTIC_DLP_METRICS_SHARDS: "{{ .Values.configMap.ELASTIC_DLP_METRICS_SHARDS }}" 
  ELASTIC_SOCKET_TIMEOUT: "{{ .Values.configMap.ELASTIC_SOCKET_TIMEOUT }}"   
  KAFKA_CONSUMER_DLP_METRICS_GROUPID: "{{ .Values.configMap.KAFKA_CONSUMER_DLP_METRICS_GROUPID }}"
  KAFKA_DLP_METRICS_CONSUMER_TOPIC: "{{ .Values.configMap.KAFKA_DLP_METRICS_CONSUMER_TOPIC }}"
  KAFKA_CONSUMER_CLASSIFICATION_DATA_GROUPID: "{{ .Values.configMap.KAFKA_CONSUMER_CLASSIFICATION_DATA_GROUPID }}"
  KAFKA_CONFIG_CLASSIFICATION_DATA_CONSUMER_TOPIC: "{{ .Values.configMap.KAFKA_CONFIG_CLASSIFICATION_DATA_CONSUMER_TOPIC }}"
  KAFKA_CONSUMER_CLUSTERED_DATA_GROUPID: "{{ .Values.configMap.KAFKA_CONSUMER_CLUSTERED_DATA_GROUPID }}"
  KAFKA_CONFIG_CLUSTERED_DATA_CONSUMER_TOPIC: "{{ .Values.configMap.KAFKA_CONFIG_CLUSTERED_DATA_CONSUMER_TOPIC }}"
  KAFKA_CONFIG_CLUSTERING_PRODUCER_TOPIC: "{{ .Values.configMap.KAFKA_CONFIG_CLUSTERING_PRODUCER_TOPIC }}"
  KAFKA_CONFIG_DATA_DEFINITION_PRODUCER_TOPIC: "{{ .Values.configMap.KAFKA_CONFIG_DATA_DEFINITION_PRODUCER_TOPIC }}"
  DEDUPLICATION_QUERY_BATCH_SIZE: "{{ .Values.configMap.DEDUPLICATION_QUERY_BATCH_SIZE }}"
  CLUSTERING_RE_CLUSTER_THRESHOLD: "{{ .Values.configMap.CLUSTERING_RE_CLUSTER_THRESHOLD }}"
  CLUSTERING_RE_CLUSTER_SCHEDULE_CRON: "{{ .Values.configMap.CLUSTERING_RE_CLUSTER_SCHEDULE_CRON }}"
  FINGERPRINTING_API: "{{ .Values.configMap.FINGERPRINTING_API }}"
  MATCHING_API: "{{ .Values.configMap.MATCHING_API }}"

  KAFKA_CONFIG_CONSUMER_GROUPID: "{{ .Values.configMap.KAFKA_CONFIG_CONSUMER_GROUPID }}"
  #KAFKA_CONFIG_CONSUMER_TOPIC: "{{ .Values.configMap.KAFKA_CONFIG_CONSUMER_TOPIC }}"
  KAFKA_CONFIG_CONNECTOR_PRODUCER_TOPIC: "{{ .Values.configMap.KAFKA_CONFIG_CONNECTOR_PRODUCER_TOPIC }}"
  KAFKA_CONFIG_PRODUCER_CONTENT_DELETION_TOPIC: "{{ .Values.configMap.KAFKA_CONFIG_PRODUCER_CONTENT_DELETION_TOPIC }}"


  DB_DDL: "{{ .Values.configMap.DB_DDL }}"
  DB_SHOW_SQL: "{{ .Values.configMap.DB_SHOW_SQL }}"
  REDISSON_URL: "{{ .Values.configMap.REDISSON_URL }}"
  REDISSON_MIN_IDLE_SIZE: "{{ .Values.configMap.REDISSON_MIN_IDLE_SIZE }}"
  REDISSON_POOL_SIZE: "{{ .Values.configMap.REDISSON_POOL_SIZE }}"
  DLP_DATA_DEFINITION_SERVICE_URL: "{{ .Values.configMap.DLP_DATA_DEFINITION_SERVICE_URL }}"
 
  KAFKA_CONSUMER_GROUPID: "{{ .Values.configMap.KAFKA_CONSUMER_GROUPID }}"
  KAFKA_CONFIG_PRODUCER_CONTENT_PROCESSOR_TOPIC: "{{ .Values.configMap.KAFKA_CONFIG_PRODUCER_CONTENT_PROCESSOR_TOPIC }}"
  KAFKA_CONFIG_PRODUCER_CONTENT_DOWNLOAD_TOPIC: "{{ .Values.configMap.KAFKA_CONFIG_PRODUCER_CONTENT_DOWNLOAD_TOPIC }}"
  KAFKA_CONFIG_PRODUCER_CONTENT_DOWNLOAD_TOPIC: "{{ .Values.configMap.KAFKA_CONFIG_PRODUCER_CONTENT_DOWNLOAD_TOPIC }}"
  KAFKA_CONFIG_DELETION_TOPIC_CONSUMER: "{{ .Values.configMap.KAFKA_CONFIG_DELETION_TOPIC_CONSUMER }}"

  KAFKA_CONSUMER_DATA_DEFINITION_GROUPID: "{{ .Values.configMap.KAFKA_CONSUMER_DATA_DEFINITION_GROUPID }}"
  KAFKA_CONFIG_DATA_DEFINITION_CONSUMER_TOPIC: "{{ .Values.configMap.KAFKA_CONFIG_DATA_DEFINITION_CONSUMER_TOPIC }}"
  DATA_DEFINITION_API: "{{ .Values.configMap.DATA_DEFINITION_API }}"
  SUMMARY_API: "{{ .Values.configMap.SUMMARY_API }}"
  CLASSIFICATION_API: "{{ .Values.configMap.CLASSIFICATION_API }}"
  FINGERPRINTING_API: "{{ .Values.configMap.FINGERPRINTING_API }}"
  
  ENVIRONMENT: "{{ .Values.configMap.ENVIRONMENT }}"
  MODEL_PATH: "{{ .Values.configMap.MODEL_PATH }}"
  MODEL_VERSION_GPT: "{{ .Values.configMap.MODEL_VERSION_GPT }}"
  MODEL_VERSION_CLAUDE: "{{ .Values.configMap.MODEL_VERSION_CLAUDE }}"
  MODEL_VERSION_GEMINI: "{{ .Values.configMap.MODEL_VERSION_GEMINI }}"
  RESULTS_DIR: "{{ .Values.configMap.RESULTS_DIR }}"

  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.configMap.KAFKA_BOOTSTRAP_SERVERS }}"
  CONSUMER_GROUP_ID_SUMMARY: "{{ .Values.configMap.CONSUMER_GROUP_ID_SUMMARY }}"
  CONSUMER_GROUP_ID_CLASSIFICATION: "{{ .Values.configMap.CONSUMER_GROUP_ID_CLASSIFICATION }}"
  CONSUMER_GROUP_ID_CLUSTERING: "{{ .Values.configMap.CONSUMER_GROUP_ID_CLUSTERING }}"
  CONSUMER_GROUP_ID_SENSITIVITY: "{{ .Values.configMap.CONSUMER_GROUP_ID_SENSITIVITY }}"
  CONSUMER_GROUP_ID_INFERENCE_PATHWAY_BINARY: "{{ .Values.configMap.CONSUMER_GROUP_ID_INFERENCE_PATHWAY_BINARY }}"
  CONSUMER_GROUP_ID_INFERENCE_PATHWAY: "{{ .Values.configMap.CONSUMER_GROUP_ID_INFERENCE_PATHWAY }}"
  CONSUMER_GROUP_ID_FINGERPRINT: "{{ .Values.configMap.CONSUMER_GROUP_ID_FINGERPRINT }}"
  CONSUMER_GROUP_ID_MATCH: "{{ .Values.configMap.CONSUMER_GROUP_ID_MATCH }}"
  CONSUMER_GROUP_ID_CLUSTER_FILE: "{{ .Values.configMap.CONSUMER_GROUP_ID_CLUSTER_FILE }}"
  KAFKA_INPUT_TOPIC_SUMMARY: "{{ .Values.configMap.KAFKA_INPUT_TOPIC_SUMMARY }}"
  KAFKA_OUTPUT_TOPIC_SUMMARY: "{{ .Values.configMap.KAFKA_OUTPUT_TOPIC_SUMMARY }}"
  KAFKA_INPUT_TOPIC_CLASSIFICATION: "{{ .Values.configMap.KAFKA_INPUT_TOPIC_CLASSIFICATION }}"
  KAFKA_OUTPUT_TOPIC_CLASSIFICATION: "{{ .Values.configMap.KAFKA_OUTPUT_TOPIC_CLASSIFICATION }}"
  KAFKA_INPUT_TOPIC_CLUSTERING: "{{ .Values.configMap.KAFKA_INPUT_TOPIC_CLUSTERING }}"
  KAFKA_OUTPUT_TOPIC_CLUSTERING: "{{ .Values.configMap.KAFKA_OUTPUT_TOPIC_CLUSTERING }}"
  KAFKA_INPUT_TOPIC_SENSITIVITY: "{{ .Values.configMap.KAFKA_INPUT_TOPIC_SENSITIVITY }}"
  KAFKA_OUTPUT_TOPIC_SENSITIVITY: "{{ .Values.configMap.KAFKA_OUTPUT_TOPIC_SENSITIVITY }}"
  KAFKA_INPUT_TOPIC_INFERENCE_PATHWAY_BINARY: "{{ .Values.configMap.KAFKA_INPUT_TOPIC_INFERENCE_PATHWAY_BINARY }}"
  KAFKA_OUTPUT_TOPIC_INFERENCE_PATHWAY_BINARY: "{{ .Values.configMap.KAFKA_OUTPUT_TOPIC_INFERENCE_PATHWAY_BINARY }}"
  KAFKA_INPUT_TOPIC_INFERENCE_PATHWAY: "{{ .Values.configMap.KAFKA_INPUT_TOPIC_INFERENCE_PATHWAY }}"
  KAFKA_OUTPUT_TOPIC_INFERENCE_PATHWAY: "{{ .Values.configMap.KAFKA_OUTPUT_TOPIC_INFERENCE_PATHWAY }}"
  KAFKA_INPUT_TOPIC_FINGERPRINT: "{{ .Values.configMap.KAFKA_INPUT_TOPIC_FINGERPRINT }}"
  KAFKA_OUTPUT_TOPIC_FINGERPRINT: "{{ .Values.configMap.KAFKA_OUTPUT_TOPIC_FINGERPRINT }}"
  KAFKA_INPUT_TOPIC_MATCH: "{{ .Values.configMap.KAFKA_INPUT_TOPIC_MATCH }}"
  KAFKA_OUTPUT_TOPIC_MATCH: "{{ .Values.configMap.KAFKA_OUTPUT_TOPIC_MATCH }}"
  KAFKA_INPUT_TOPIC_CLUSTER_FILE: "{{ .Values.configMap.KAFKA_INPUT_TOPIC_CLUSTER_FILE }}"
  KAFKA_OUTPUT_TOPIC_CLUSTER_FILE: "{{ .Values.configMap.KAFKA_OUTPUT_TOPIC_CLUSTER_FILE }}"

  ES_HOST: "{{ .Values.configMap.ES_HOST }}"
  ES_USER_NAME: "{{ .Values.configMap.ES_USER_NAME }}"

  VAULT_PROTOCOL: "{{ .Values.configMap.VAULT_PROTOCOL }}"
  VAULT_HOST: "{{ .Values.configMap.VAULT_HOST }}"
  VAULT_PORT: "{{ .Values.configMap.VAULT_PORT }}"
  DLP_DATA_DEFINITION_URL: "{{ .Values.configMap.DLP_DATA_DEFINITION_URL }}"
  OOB_DDs: "{{ .Values.configMap.OOB_DDs }}"  
  AI_SERVICE_URL:  "{{ .Values.configMap.AI_SERVICE_URL }}"

  







  
     
 
