namespace: quilr
quilr:
  appname: dlp-metrics-service
configMap: {}
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: 975050335771.dkr.ecr.us-east-1.amazonaws.com/main/dlp-metrics-service
  tag: latest
  pullPolicy: Always
resources:
  requests:
    memory: "1024Mi"
    cpu: "125m"
  limits:
    memory: "2048Mi"
    cpu: "1000m"
secretRef:
  name: auth-key-public
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
service:
  name: dlp-metrics-service
  type: ClusterIP
  port: 8044
  targetPort: 8044
# Additional fields
secrets:
  elastictrustrore: quilr-elasticsearch-db-trustore
