## No service specific configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Values.quilr.appname }}-configmap
  namespace: {{ .Values.namespace | default "default" }}  # Use namespace from values.yaml
data:
  SUPPORTED_EXTN_TYPES: "{{ .Values.configMap.SUPPORTED_EXTN_TYPES }}"
  
