## values.yaml
#****************** for deployment.yaml ******************#
namespace: quilr
quilr:
  appname: email-transformation-service
### for hpa.yaml
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
image:
  repository: 975050335771.dkr.ecr.ap-south-1.amazonaws.com/main/email-transformation-service
  tag: latest
  pullPolicy: Always
configMap:
  KAFKA_TOPIC_READ: "emailsRaw"
  KAFKA_TOPIC_WRITE: "transformedOutput"
  KAFKA_GROUP_ID: "email-transformation"
  SERVICE_NAME: "email-transformation-service"
secretRef:
  name: auth-key-public
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
    #################service-name: event-transformation-service ###################################################################
#****************** for service.yaml ******************#
service:
  name: email-transformation-service
  type: ClusterIP
  port: 9003
  targetPort: 9003
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
########################################################################
