apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.quilr.appname }}-configmap
  namespace: {{ .Values.namespace | default "quilr" }}  # Use namespace from values.yaml
data:
  SERVICE_NAME: "{{ .Values.configMap.SERVICE_NAME }}"
  # KAFKA_BROKER: "{{ .Values.configMap.KAFKA_BROKER }}"
  KAFKA_GROUP_ID: "{{ .Values.configMap.KAFKA_GROUP_ID }}"
  # KAFKA_BOOTSTRAP_SERVER: "{{ .Values.configMap.KAFKA_BOOTSTRAP_SERVER }}"
  TOPIC_GRAPH_QUERY: "{{ .Values.configMap.TOPIC_GRAPH_QUERY }}"
  # REDIS_HOST: "{{ .Values.configMap.REDIS_HOST }}"
  # REDIS_PORT: "{{ .Values.configMap.REDIS_PORT }}"
  # REDIS_DB: "{{ .Values.configMap.REDIS_DB }}"
  # REDIS_PASSWORD: "{{ .Values.configMap.REDIS_PASSWORD }}"
  #GLOBAL_APP_SERVER_URL: "{{ .Values.configMap.GLOBAL_APP_SERVER_URL }}"
