apiVersion: v1
kind: ConfigMap
metadata:
  name: quilr-common-config
  namespace: {{ .Values.namespace | default "quilr" }}  # Use namespace from values.yaml
data:
  KAFKA_BROKER_HOST: "{{ .Values.configMap.KAFKA_BROKER_HOST }}"
  KAFKA_BROKER: "{{ .Values.configMap.KAFKA_BROKER }}"
  KAFKA_BOOTSTRAP_SERVER: "{{ .Values.configMap.KAFKA_BOOTSTRAP_SERVER }}"
  KAFKA_BROKER_PORT: "{{ .Values.configMap.KAFKA_BROKER_PORT }}"
  PG_PORT: "{{ .Values.configMap.PG_PORT }}"
  PG_DB: "{{ .Values.configMap.PG_DB }}"
  PG_DATABASE: "{{ .Values.configMap.PG_DATABASE }}"
  PG_AUTH_DB: "{{ .Values.configMap.PG_AUTH_DB }}"
  REDIS_HOST: "{{ .Values.configMap.REDIS_HOST }}"
  REDIS_PORT: "{{ .Values.configMap.REDIS_PORT }}"
  REDIS_DB: "{{ .Values.configMap.REDIS_DB }}"
  VAULT_HOST: "{{ .Values.configMap.VAULT_HOST }}"
  VAULT_ADDR: "{{ .Values.configMap.VAULT_ADDR }}"
  VAULT_BASE_URL: "{{ .Values.configMap.VAULT_BASE_URL }}"
  VAULT_PORT: "{{ .Values.configMap.VAULT_PORT }}"
  VAULT_PROTOCOL: "{{ .Values.configMap.VAULT_PROTOCOL }}"
  SEARCH_API_ENDPOINT: "{{ .Values.configMap.SEARCH_API_ENDPOINT }}"
  SEARCH_SERVICE_HOST: "{{ .Values.configMap.SEARCH_SERVICE_HOST }}"
  SEARCH_SERVICE_PORT: "{{ .Values.configMap.SEARCH_SERVICE_PORT }}"
  SEARCH_API_HOST: "{{ .Values.configMap.SEARCH_API_HOST }}"
  SEARCH_API_PORT: "{{ .Values.configMap.SEARCH_API_PORT }}"
  SEARCH_SERVICE_URL: "{{ .Values.configMap.SEARCH_SERVICE_URL }}"
  SEARCH_SERVICE: "{{ .Values.configMap.SEARCH_SERVICE }}"
  LAMBDA_SERVICE_HOST: "{{ .Values.configMap.LAMBDA_SERVICE_HOST }}"
  LAMBDA_SERVICE_PORT: "{{ .Values.configMap.LAMBDA_SERVICE_PORT }}"
  TRACKING_SERVICE_HOST: "{{ .Values.configMap.TRACKING_SERVICE_HOST }}"
  TRACKING_SERVICE_PORT: "{{ .Values.configMap.TRACKING_SERVICE_PORT }}"
  TRACKING_API_HOST: "{{ .Values.configMap.TRACKING_API_HOST }}"
  TRACKING_API_PORT: "{{ .Values.configMap.TRACKING_API_PORT }}"
  CONTENT_SERVER_URL: "{{ .Values.configMap.CONTENT_SERVER_URL }}"
  INSTANCE_MANAGER_SERVICE_HOST: "{{ .Values.configMap.INSTANCE_MANAGER_SERVICE_HOST }}"
  INSTANCE_MANAGER_SERVICE_PORT: "{{ .Values.configMap.INSTANCE_MANAGER_SERVICE_PORT }}"
  CLASSIFICATION_REPOSITORY_URL: "{{ .Values.configMap.CLASSIFICATION_REPOSITORY_URL }}"
  CONTENT_REPO_URI: "{{ .Values.configMap.CONTENT_REPO_URI }}"
  REPOSITORY_API_HOST: "{{ .Values.configMap.REPOSITORY_API_HOST }}"
  REPOSITORY_API_PORT: "{{ .Values.configMap.REPOSITORY_API_PORT }}"
  AUTH_API_HOST: "{{ .Values.configMap.AUTH_API_HOST }}"
  AUTH_API_PORT: "{{ .Values.configMap.AUTH_API_PORT }}"
  AUTH_API_CLIENT: "{{ .Values.configMap.AUTH_API_CLIENT }}"
  AUTH_API_PORT: "{{ .Values.configMap.AUTH_API_PORT }}"
  QUILR_AUTH: "{{ .Values.configMap.QUILR_AUTH }}"
  SCHEDULER_API_HOST: "{{ .Values.configMap.SCHEDULER_API_HOST }}"
  SCHEDULER_API_PORT: "{{ .Values.configMap.SCHEDULER_API_PORT }}"
  SCHEDULER_SERVICE_HOST: "{{ .Values.configMap.SCHEDULER_SERVICE_HOST }}"
  SCHEDULER_SERVICE_PORT: "{{ .Values.configMap.SCHEDULER_SERVICE_PORT }}"
  PLAYBOOK_API_HOST: "{{ .Values.configMap.PLAYBOOK_API_HOST }}"
  PLAYBOOK_API_PORT: "{{ .Values.configMap.PLAYBOOK_API_PORT }}"
  RESPONSE_GATEWAY_HOST: "{{ .Values.configMap.RESPONSE_GATEWAY_HOST }}"
  RESPONSE_GATEWAY_PORT: "{{ .Values.configMap.RESPONSE_GATEWAY_PORT }}"
  SELF_HOST: "{{ .Values.configMap.SELF_HOST }}"
  SELF_PORT: "{{ .Values.configMap.SELF_PORT }}"
  LLM_SERVICE_HOST: "{{ .Values.configMap.LLM_SERVICE_HOST }}"
  LLM_SERVICE_PORT: "{{ .Values.configMap.LLM_SERVICE_PORT }}"
  MAIL_HOST: "{{ .Values.configMap.MAIL_HOST }}"
  MAIL_PORT: "{{ .Values.configMap.MAIL_PORT }}"
  MAIL_PROTOCOL: "{{ .Values.configMap.MAIL_PROTOCOL }}"
  EMAIL_API_HOST: "{{ .Values.configMap.EMAIL_API_HOST }}"
  EMAIL_API_PORT: "{{ .Values.configMap.EMAIL_API_PORT }}"
  EMAIL_SERVICE: "{{ .Values.configMap.EMAIL_SERVICE }}"
  TEMPLATE_API_HOST: "{{ .Values.configMap.TEMPLATE_API_HOST }}"
  TEMPLATE_API_PORT: "{{ .Values.configMap.TEMPLATE_API_PORT }}"
  DATA_CONFIG_API_HOST: "{{ .Values.configMap.DATA_CONFIG_API_HOST }}"
  DATA_CONFIG_API_PORT: "{{ .Values.configMap.DATA_CONFIG_API_PORT }}"
  QUILR_DATA_HARVESTER_SERVICE: "{{ .Values.configMap.QUILR_DATA_HARVESTER_SERVICE }}"
  QUILR_BROWSER_EXTENSION_SERVICE: "{{ .Values.configMap.QUILR_BROWSER_EXTENSION_SERVICE }}"
  APP_SYNC_API_ENDPOINT: "{{ .Values.configMap.APP_SYNC_API_ENDPOINT }}"
  RAG_DOMAIN: "{{ .Values.configMap.RAG_DOMAIN }}"
  APP_SYNC_SERVICE_HOST: "{{ .Values.configMap.APP_SYNC_SERVICE_HOST }}"
  APP_SYNC_SERVICE_PORT: "{{ .Values.configMap.APP_SYNC_SERVICE_PORT }}"
  QUILR_SEARCH_SERVICE: "{{ .Values.configMap.QUILR_SEARCH_SERVICE }}"
  QUILR_SCHEDULER_SERVICE: "{{ .Values.configMap.QUILR_SCHEDULER_SERVICE }}"
  QUILR_USER_RESPONSE_SERVICE: "{{ .Values.configMap.QUILR_USER_RESPONSE_SERVICE }}"
  QUILR_AGENT_SERVICE: "{{ .Values.configMap.QUILR_AGENT_SERVICE }}"
  CLASSIFIER_DOMAIN: "{{ .Values.configMap.CLASSIFIER_DOMAIN }}"
  COLLECTOR_DOMAIN: "{{ .Values.configMap.COLLECTOR_DOMAIN }}"
  QUILR_PLAYBOOK_SERVICE: "{{ .Values.configMap.QUILR_PLAYBOOK_SERVICE }}"
  DEFAULT_KNOWLEDGE_DB: "{{ .Values.configMap.DEFAULT_KNOWLEDGE_DB }}"
  Neo4J_LLAMA_ENDPOINT: "{{ .Values.configMap.Neo4J_LLAMA_ENDPOINT }}"
  OPENAI_MINI_BASE_URL: "{{ .Values.configMap.OPENAI_MINI_BASE_URL }}"
  OPENAI_EMBEDDING_BASE_URL: "{{ .Values.configMap.OPENAI_EMBEDDING_BASE_URL }}"
  OPENAI_LATEST_BASE_URL: "{{ .Values.configMap.OPENAI_LATEST_BASE_URL }}"
  SLACK_INTEGRATION_URL: "{{ .Values.configMap.SLACK_INTEGRATION_URL }}"
  AGENT_SERVICE_HOST: "{{ .Values.configMap.AGENT_SERVICE_HOST }}"
  AGENT_SERVICE_PORT: "{{ .Values.configMap.AGENT_SERVICE_PORT }}"
  DLP_DATA_DEFINITION_URL: "{{ .Values.configMap.DLP_DATA_DEFINITION_URL }}"
  OOB_DDs: "{{ .Values.configMap.OOB_DDs }}"
  AI_SERVICE_URL:  "{{ .Values.configMap.AI_SERVICE_URL }}" 
  CLASSIFICATION_CONFIG_API_HOST: "{{ .Values.configMap.CLASSIFICATION_CONFIG_API_HOST }}" 
  ELASTIC_URL: "{{ .Values.configMap.ELASTIC_URL }}" 
  DLP_UPDATE_URL: "{{ .Values.configMap.DLP_UPDATE_URL }}" 
  QUILR_MCP_MEMORY_SERVICE: "{{ .Values.configMap.QUILR_MCP_MEMORY_SERVICE }}" 
  AZURE_BLOB_URL: "{{ .Values.configMap.AZURE_BLOB_URL }}" 
  OIDCIssuer: "{{ .Values.configMap.OIDCIssuer }}"
  OIDC_MICROSOFT_CLIENT_ID: "{{ .Values.configMap.OIDC_MICROSOFT_CLIENT_ID }}"
  # Moved to Vault
  # OPENAI_LATEST_API_KEY: "{{ .Values.configMap.OPENAI_LATEST_API_KEY }}"
  # OPENAI_MINI_API_KEY: "{{ .Values.configMap.OPENAI_MINI_API_KEY }}"
  # OPENAI_EMBEDDING_API_KEY: "{{ .Values.configMap.OPENAI_EMBEDDING_API_KEY }}"
  # SLACK_OAUTH_CLIENT_ID": 
  # SLACK_OAUTH_CLIENT_SECRET": 
  AZURE_BLOB_URL: "{{ .Values.configMap.AZURE_BLOB_URL }}"
  AI_SERVICE_URL: "{{ .Values.configMap.AI_SERVICE_URL }}"
  ELASTIC_URL: "{{ .Values.configMap.ELASTIC_URL }}"
  DLP_UPDATE_URL: "{{ .Values.configMap.DLP_UPDATE_URL }}"
  QUILR_MCP_MEMORY_SERVICE: "{{ .Values.configMap.QUILR_MCP_MEMORY_SERVICE }}"
  #OIDCIssuer: "{{ .Values.configMap.OIDCIssuer }}"
  #OIDC_MICROSOFT_CLIENT_ID: "{{ .Values.configMap.OIDC_MICROSOFT_CLIENT_ID }}"  
  AI_SERVICE_URL: "{{ .Values.configMap.AI_SERVICE_URL }}"
  ELASTIC_URL: "{{ .Values.configMap.ELASTIC_URL }}"
  DLP_UPDATE_URL: "{{ .Values.configMap.DLP_UPDATE_URL }}"
  QUILR_MCP_MEMORY_SERVICE: "{{ .Values.configMap.QUILR_MCP_MEMORY_SERVICE }}"
  OIDCIssuer: "{{ .Values.configMap.OIDCIssuer }}"
  OIDC_MICROSOFT_CLIENT_ID: "{{ .Values.configMap.OIDC_MICROSOFT_CLIENT_ID }}"
  CONTENT_KNOWLEDGE_SERVICE_HOST: "{{ .Values.configMap.CONTENT_KNOWLEDGE_SERVICE_HOST }}"
  CONTENT_KNOWLEDGE_SERVICE_PORT: "{{ .Values.configMap.CONTENT_KNOWLEDGE_SERVICE_PORT }}"
  EXTENATION_BASE_URL: "{{ .Values.configMap.EXTENATION_BASE_URL }}"
  EXTENAION_VERSION_FILE: "{{ .Values.configMap.EXTENAION_VERSION_FILE }}"
  DLP_MAIN_SERVER_URL:  "{{ .Values.configMap.DLP_MAIN_SERVER_URL }}"
  STORAGE_CONTAINER_NAME: "{{ .Values.configMap.STORAGE_CONTAINER_NAME }}"
  STORAGE_ICON_CONTAINER_NAME: "{{ .Values.configMap.STORAGE_ICON_CONTAINER_NAME }}"
  BASE_URL: "{{ .Values.configMap.BASE_URL }}"
  DEPLOYMENT_TYPE: "{{ .Values.configMap.DEPLOYMENT_TYPE }}"
  MicrosoftBotAppId: "{{ .Values.configMap.MicrosoftBotAppId }}"
  MicrosoftBotAppPassword: "{{ .Values.configMap.MicrosoftBotAppPassword }}"
  quilr_base_url: "{{ .Values.configMap.quilr_base_url }}" 
  DW_HOST: "{{ .Values.configMap.DW_HOST }}"
  DW_PORT: "{{ .Values.configMap.DW_PORT }}"
  DW_NAME: "{{ .Values.configMap.DW_NAME }}"
  DW_USER: "{{ .Values.configMap.DW_USER }}"
  DLP_RESPONSE_URL: "{{ .Values.configMap.DLP_RESPONSE_URL }}"
  PROMPT_CATEGORIZATION_URL: "{{ .Values.configMap.PROMPT_CATEGORIZATION_URL }}"
  SIEM_SERVICE_HOST: "{{ .Values.configMap.SIEM_SERVICE_HOST }}"
  SIEM_SERVICE_PORT: "{{ .Values.configMap.SIEM_SERVICE_PORT }}"
  QUERY_BUILDER_SERVICE_HOST: "{{ .Values.configMap.QUERY_BUILDER_SERVICE_HOST }}"
  QUERY_BUILDER_SERVICE_PORT: "{{ .Values.configMap.QUERY_BUILDER_SERVICE_PORT }}"
  EXTENSION_API_SERICE_HOST: "{{ .Values.configMap.EXTENSION_API_SERICE_HOST }}"
  EXTENSION_API_SERICE_PORT: "{{ .Values.configMap.EXTENSION_API_SERICE_PORT }}"
  TRANSFORMATION_SERVICE_HOST: "{{ .Values.configMap.TRANSFORMATION_SERVICE_HOST }}"
  TRANSFORMATION_SERVICE_PORT: "{{ .Values.configMap.TRANSFORMATION_SERVICE_PORT }}"