## No service specific configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Values.quilr.appname }}-configmap
  namespace: {{ .Values.namespace | default "default" }}  # Use namespace from values.yaml
data:
  ELASTIC_TRUST_STORE_LOCATION: 'file:/{{ .Values.quilr.appname }}-truststore/truststore.jks'
