type: message
content:
  acknowledgedButtons:
  - id: 3355f927-522d-471b-af1c-cbb12c07ff5a
    account: true
    isPrimary: true
    name: App is company-approved
    whitelist: false
  - id: 84851c91-b353-4ef9-98da-9b19565c81ce
    account: true
    isPrimary: false
    name: Acknowledge warning
    whitelist: false
  - id: 6c6168e2-9c39-404e-a9df-9028a87c17fd
    account: true
    isPrimary: false
    name: Have Prior Approval
    whitelist: false
  - id: c0f4a538-ce90-4404-88f8-1765b2c2ea15
    account: true
    isPrimary: false
    name: Urgent for critical task
    whitelist: false
  justification_list:
  - It’s blocking my productivity.
  - I can’t do my job without this.
  - This is an industry-standard app, why is it blocked?
  - I have approval from my manager to use this app.
  - The official app doesn't support what I need.
  - I didn't know it wasn't allowed.
  - It is just a one-time thing.
  - We are racing against a deadline.
  - Everyone else in the team is using it.
  - Something else.
  header: Heads up!
  description: ""
  title: |
    It looks like you're using an unapproved AI app. For your security and privacy, we recommend switching to an approved tool.

    <br />Your actions matter — help keep your organization safe!
channel: Browser
rendered_content_type: application/json
name: Block using an unapproved AI app
is_active: true

