name: Prompt to change compromised password post login on a critical application
type: message
channel: Browser
content:
  header: "Warning: Compromised Password!"
  title: |
    Your password may have been exposed.
    <br />Please update it to something stronger or use a password manager. Help keep your account safe!
    <br />
    <br />A compromised password is one that has been stolen or exposed, allowing someone else to access your account, and steal your company information.
    <br  />
    <br />Your actions matter â€” help keep your organization safe!
  description: ""
  acknowledgedButtons:
    - id: f9c6915d-d36f-4944-900d-5c72d941d970
      isPrimary: true
      name: "Using a strong password  "
      whitelist: false
    - id: a4b70eee-e3a6-4562-8117-9d3b13c654ca
      isPrimary: false
      name: "Will change my password"
      whitelist: false  
rendered_content_type: application/json
is_active: true
# generic prompt for weak password on a critical app - important is critical