name: Prompt to change weak password during signup
type: message
channel: Browser
content:
  header: "Warning: Weak Password!"
  title: |
    You're using a weak password. Please update it to something stronger—mix letters, numbers, and symbols, or use a password manager. Weak passwords are easy to guess and put your account at risk!
    <br  />
    <br />Your actions matter — help keep your organization safe!
description: ""
acknowledgedButtons:
  - id: 7a2bd603-7c26-4586-a28c-cf27d3f0266e
    isPrimary: true
    name: "Using a strong password"
    whitelist: false
  - id: 0cb30d1b-396d-4ebd-8068-eaa6b2a751d1
    isPrimary: false
    name: "Will change my password"
    whitelist: false
rendered_content_type: application/json
is_active: true
# sign up = new account