name: Block copying business data
type: message
channel: Browser
content:
  header: "Business Data Copied"
  title: |
    Looks like you copied business critical information. Please avoid it and if you have to, please provide a business justification.
    <br />
    <br /> Copying business critical information is not a recommended security best practice.
  description: "*Specify business justification?*"
rendered_content_type: application/json
is_active: true