name: Prompt to change compromised password during signup
type: message
channel: Browser
content:
  header: "Warning: Compromised Password!"
  title: |
    You're using a compromised password. Please update it with something stronger to protect your account and company info!
    <br  />
    <br />Your actions matter â€” help keep your organization safe!
  description: ""
  acknowledgedButtons:
    - id: 0e35c464-802b-4a16-b3c7-82199ad32641
      isPrimary: true
      name: "Using a strong password"
      whitelist: false
    - id: fe4728a1-a9f2-41dd-86d6-7b0759429c11
      isPrimary: false
      name: "Will change my password"
      whitelist: false

rendered_content_type: application/json
is_active: true
# generic prompt for weak password on a critical app - important is critical