name: Warn on using an AI app not seen before
type: message
channel: Browser
content:
  header: "Hey! Just a quick heads-up!"
  title: |
    Looks like you are using a new AI app. No doubt AI's awesome, but it's not perfect — double-check important info. Be careful with personal data, and keep an eye out for any biases. Always trust your judgment along with AI. Have fun exploring!
       
    <br />Your actions matter — help keep your organization safe!
  description: ""
  acknowledgedButtons:
    - id: 9e866b2f-8f8d-4bf1-a5cb-0eec72e23c87
      isPrimary: true
      name: "Acknowledge warning"
      whitelist: false
rendered_content_type: application/json
is_active: true
