name: Prompt using a breached SaaS app
type: message
channel: Browser
content:
  header: "Hey! Just a quick heads-up!"
  title: |
    It looks like you're about to use a breached SaaS app.
    <br />If you have an account on this app, please change your password immediately.
    <br />If you don't have an account, please reconsider using this app.
       
    <br />Your actions matter â€” help keep your organization safe!
  description: ""
  acknowledgedButtons:
    - id: b181c59b-2c42-4042-9162-d783ecb3bfc0
      isPrimary: true
      name: "Acknowledge warning"
      whitelist: false
rendered_content_type: application/json
is_active: true
