namespace: quilr

configMap:
  #SERVER_PORT: "8044"
  KAFKA_BROKERS: "kafka-server:9092"
  ELASTIC_URL: "https://quilr-db-elasticsearch:9200"
  ELASTIC_USERNAME: "elastic"
  ELASTIC_CONNECTION_TIMEOUT: "5000"
  ELASTIC_READ_TIMEOUT: "5000"
  ELASTIC_REST_ENABLED: "true" 
  ELASTIC_REPOSITORIES_ENABLED: "true"
  ELASTIC_CONNECTION_POOL: "5" 
  KAFKA_CONSUMER_DEDUPLICATION_GROUPID: "dlp-deduplication-groupid"
  KAFKA_OFFSET: "earliest"
  KAFKA_KEY_DESERIALIZER: "org.apache.kafka.common.serialization.StringDeserializer"
  KAFKA_VALUE_DESERIALIZER: "org.apache.kafka.common.serialization.StringDeserializer"
  KAFKA_CONFIG_DEDUPLICATION_CONSUMER_TOPIC: "dlp-deduplication-topic"
  KAFKA_CONFIG_CLASSIFICATION_PRODUCER_TOPIC: "dlp-classification-topic"
  KAFKA_CONFIG_DELETION_CONSUMER_GROUPID: "dlp-deletion-groupid"
  KAFKA_CONFIG_INDEXER_CONSUMER_GROUPID: "dlp-indexer-groupid"
  KAFKA_CONFIG_INDEXER_CONSUMER_TOPIC: "dlp-indexer-topic"
  KAFKA_CONFIG_DEDUPLICATION_PRODUCER_TOPIC: "dlp-deduplication-topic"
  FILES_DOWNLOAD_LOCATION: "/dlp-download-storage-prod-sentara"
  DLP_DEDUPLICATION_SERVICE_URL: "http://dlp-deduplication-service:8041/dlp/dedup"
  REDIS_PORT: "6379"
  REDIS_TIMEOUT: "2000"
  REDIS_HOST: "my-redis-master"
  ELASTIC_DLP_METRICS_REPLICAS: "1"
  ELASTIC_DLP_METRICS_SHARDS: "1"
  ELASTIC_SOCKET_TIMEOUT: "30000"
  KAFKA_CONSUMER_DLP_METRICS_GROUPID: "dlp-metrics-groupid"
  KAFKA_DLP_METRICS_CONSUMER_TOPIC: "dlp-metrics-topic"
  KAFKA_CONSUMER_CLASSIFICATION_DATA_GROUPID: "dlp-classification-data-groupid"
  KAFKA_CONFIG_CLASSIFICATION_DATA_CONSUMER_TOPIC: "dlp-classification-data-topic"
  KAFKA_CONSUMER_CLUSTERED_DATA_GROUPID: "dlp-clustered-data-groupid"
  KAFKA_CONFIG_CLUSTERED_DATA_CONSUMER_TOPIC: "dlp-clustered-data-topic"
  KAFKA_CONFIG_CLUSTERING_PRODUCER_TOPIC: "dlp-clustering-topic"
  KAFKA_CONFIG_DATA_DEFINITION_PRODUCER_TOPIC: "dlp-data-definition-topic"
  DEDUPLICATION_QUERY_BATCH_SIZE: "50"
  CLUSTERING_RE_CLUSTER_THRESHOLD: "10"
  CLUSTERING_RE_CLUSTER_SCHEDULE_CRON: "0 0/30 * * * *"
  FINGERPRINTING_API: "http://quilr-ai-services:8050/fingerprint"
  MATCHING_API: "http://quilr-ai-services-test:8050/match"
  KAFKA_CONFIG_CONSUMER_GROUPID: "dlp-config-groupid"
  #KAFKA_CONFIG_CONSUMER_TOPIC: "dlp-config-topic"
  KAFKA_CONFIG_CONNECTOR_PRODUCER_TOPIC: "dlp-connector-topic"
  KAFKA_CONFIG_PRODUCER_CONTENT_DELETION_TOPIC: "dlp-content-deletion-topic" 
  DB_DDL: "update"
  DB_SHOW_SQL: "true"
  REDISSON_URL: "redis://my-redis-master:6379"
  REDISSON_MIN_IDLE_SIZE: "5"
  REDISSON_POOL_SIZE: "10"
  DLP_DATA_DEFINITION_SERVICE_URL: "http://dlp-data-definition-service:8046/dlp/dataDefinition"
  KAFKA_CONSUMER_GROUPID: "dlp-connector-groupid"
  KAFKA_CONFIG_PRODUCER_CONTENT_PROCESSOR_TOPIC: "dlp-content-processor-topic"
  KAFKA_CONFIG_PRODUCER_CONTENT_DOWNLOAD_TOPIC: "dlp-content-download-topic"
  KAFKA_CONFIG_DELETION_TOPIC_CONSUMER: "dlp-content-deletion-topic"
  KAFKA_CONSUMER_DATA_DEFINITION_GROUPID: "dlp-data-definition-groupid"
  KAFKA_CONFIG_DATA_DEFINITION_CONSUMER_TOPIC: "dlp-data-definition-topic"
  DATA_DEFINITION_API: "http://quilr-ai-services:8050/datadefinition"
  SUMMARY_API: "http://quilr-ai-services:8050/summary"
  CLASSIFICATION_API: "http://quilr-ai-services:8050/classification"
  ENVIRONMENT: "development"
  MODEL_PATH: "all-MiniLM-L6-v2"
  MODEL_VERSION_GPT: "gpt-4o-mini"
  MODEL_VERSION_CLAUDE: "claude-3-opus-20240229"
  MODEL_VERSION_GEMINI: "gemini-pro"  
  RESULTS_DIR: "data_definition_results"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-server:9092"
  CONSUMER_GROUP_ID_SUMMARY: "ai-consumer-group-id-summary"
  CONSUMER_GROUP_ID_CLASSIFICATION: "ai-consumer-group-id-classification"
  CONSUMER_GROUP_ID_CLUSTERING: "ai-consumer-group-id-clustering"
  CONSUMER_GROUP_ID_SENSITIVITY: "ai-consumer-group-id-sensitivity"
  CONSUMER_GROUP_ID_INFERENCE_PATHWAY_BINARY: "ai-consumer-group-id-inference-pathway-binary"
  CONSUMER_GROUP_ID_INFERENCE_PATHWAY: "ai-consumer-group-id-inference-pathway"
  CONSUMER_GROUP_ID_FINGERPRINT: "ai-consumer-group-id-fingerprint"
  CONSUMER_GROUP_ID_MATCH: "ai-consumer-group-id-match"
  CONSUMER_GROUP_ID_CLUSTER_FILE: "ai-consumer-group-id-cluster-file"
  KAFKA_INPUT_TOPIC_SUMMARY: "dlp-content-download-topic"
  KAFKA_OUTPUT_TOPIC_SUMMARY: "dlp-indexer-topic"
  KAFKA_INPUT_TOPIC_CLASSIFICATION: "dlp-classification-topic"
  KAFKA_OUTPUT_TOPIC_CLASSIFICATION: "dlp-classification-data-topic"
  KAFKA_INPUT_TOPIC_CLUSTERING: "dlp-clustering-topic"
  KAFKA_OUTPUT_TOPIC_CLUSTERING: "dlp-clustered-data-topic"
  KAFKA_INPUT_TOPIC_SENSITIVITY: "dlp-sensitivity-topic"
  KAFKA_OUTPUT_TOPIC_SENSITIVITY: "dlp-sensitivity-data-topic"
  KAFKA_INPUT_TOPIC_INFERENCE_PATHWAY_BINARY: "dlp-inference-pathway-binary-topic"
  KAFKA_OUTPUT_TOPIC_INFERENCE_PATHWAY_BINARY: "dlp-inference-pathway-binary-data-topic"
  KAFKA_INPUT_TOPIC_INFERENCE_PATHWAY: "dlp-inference-pathway-topic"
  KAFKA_OUTPUT_TOPIC_INFERENCE_PATHWAY: "dlp-inference-pathway-data-topic"
  KAFKA_INPUT_TOPIC_FINGERPRINT: "dlp-fingerprint-topic"
  KAFKA_OUTPUT_TOPIC_FINGERPRINT: "dlp-fingerprint-data-topic"
  KAFKA_INPUT_TOPIC_MATCH: "dlp-match-topic"
  KAFKA_OUTPUT_TOPIC_MATCH: "dlp-match-data-topic"
  KAFKA_INPUT_TOPIC_CLUSTER_FILE: "dlp-cluster-file-topic"
  KAFKA_OUTPUT_TOPIC_CLUSTER_FILE: "dlp-cluster-file-data-topic"
  VAULT_PROTOCOL: "https"
  VAULT_HOST: "vault.quilr.svc.cluster.local"
  VAULT_PORT: "8200"
  ES_HOST: "https://quilr-db-elasticsearch:9200"
  ES_USER_NAME: "elastic"
  DLP_DATA_DEFINITION_URL: "https://quilr.axisbank.com/bff/dlp-data-definition"
  OOB_DDs: 'PII,PFI,PHI,SECRET'
  AI_SERVICE_URL: 'http://quilr-ai-services:8050'


