apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.quilr.appname }}-configmap
  namespace: {{ .Values.namespace | default "default" }}  # Use namespace from values.yaml
data:
  SQLALCHAMY_DATABASE_URL: "{{ .Values.configMap.SQLALCHAMY_DATABASE_URL }}"
  CONFIG_FILES_DIR: "{{ .Values.configMap.CONFIG_FILES_DIR }}"
  STATIC_FILES_DIR: "{{ .Values.configMap.STATIC_FILES_DIR }}"
  LOG_FILE: "{{ .Values.configMap.LOG_FILE }}"
  DEBUG: "{{ .Values.configMap.DEBUG }}"
  QUILR_BFF_URL: "{{ .Values.configMap.QUILR_BFF_URL }}"
