id: 8131050d-096b-43e0-8fa4-1eba3bda4127
name: windows firewall is disabled or misconfigured
updatedon: 1710504494000
condition:
- filter_condition:
    condition: is not equal to
    value: ActiveFirewallRequired
    attribute_id: DEV-003
    attribute_type: ATTR_DEV_001
  filter_group: 
  operator: 
  editable: false
- filter_condition:
    condition: is not equal to
    value: compliant
    attribute_id: DEV-004
    attribute_type: ATTR_DEV_001
  filter_group: 
  operator: AND
  editable: false
createdon: 1710504494000
version: 1.10
description: This use case detects when Windows Firewall is either disabled or misconfigured. It monitors compliance settings to identify devices where the firewall status is not marked as compliant.
posture:
- PID_05
code: UC105
disabled: false
type: use-case
behavior:
- BID_104

