namespace: quilr
quilr:
  appname: browser-extension-service
  commonfileshare: quilr-data-upload
configMap:
  RELAY_CONFIG_DIR: "/browser-extension-service/static/relays"
  LOOKUP_CONFIG_DIR: "/browser-extension-service/static/lookups"
  RULE_CONFIG_DIR: "/browser-extension-service/static/rule_configurations"
  BLOB_URL: "https://staticcontent1.blob.core.windows.net/onboarding/knowYourOrg.json"
  MDM_CONFIG_DIR: "/browser-extension-service/static/mdm_configurations"
  USER_DETAILS_TTL: 600
  APP_DETAILS_TTL: 600
  ORG_DOMAIN_TTL: 600
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: quilrdev.azurecr.io/browser-extension-service
  tag: latest_prod
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "6Gi"
    cpu: "2000m"
secretRef:
  name: auth-key-public
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
service:
  name: browser-extension-service
  type: ClusterIP
  port: 8085
  targetPort: 8085
# Additional fields
secretName: azure-secret
azurefileshare:
  name: secopsquilrstgfileshare
