namespace: quilr
quilr:
  appname: data-config-api
configMap:
  SQLALCHAMY_DATABASE_URL: "sqlite:///./local.db"
  CONFIG_FILES_DIR: "/data-config-api/service_configs"
  STATIC_FILES_DIR: "/data-config-api/static"
  LOG_FILE: "logs/debug.log"
  DEBUG: "False"
  QUILR_BFF_URL: "https://quilr.axisbank.com/bff"
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: quilrdev.azurecr.io/data-config-api
  tag: latest_prod
  pullPolicy: Always
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
secretRef:
  name: auth-key-public
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
service:
  name: data-config-api
  type: ClusterIP
  port: 8000
  targetPort: 8000
# Additional fields
secretName: azure-secret
azurefileshare:
  name: secopsquilrstgfileshare
