# Namespace and application name
namespace: quilr
quilr:
  appname: quilr-purview-fabric

# CronJob-specific values
cronjob:
  schedule: "0 */6 * * *"
  concurrencyPolicy: "Forbid"
  ttlSecondsAfterFinished: "300"
  activeDeadlineSeconds: "86400"
  backoffLimit: "2"

# Vault configuration for annotations and passthrough
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  vault-env-passthrough: "VAULT_ADDR,VAULT_TOKEN"
  role: "default"
  path: "kubernetes"

# Container image configuration
image:
  repository: quilrdev.azurecr.io/quilr-purview-fabric
  tag: latest_prod
  pullPolicy: Always

configMap:
  KAFKA_TOPIC_USER: "usersRaw"
  KAFKA_TOPIC_APP: "appsRaw"
  logging_level: "INFO"
  FetchInterval: "300"
  IntegrationId: "04572064-b02e-472a-8b61-d142d567cfce"