namespace: quilr
quilr:
  appname: demo-quilr-web
### for hpa.yaml
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
image:
  repository: 975050335771.dkr.ecr.us-east-1.amazonaws.com/quilr-preprod/demo-quilr-web
  tag: latest
  pullPolicy: Always
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
configMap:
  bffurl: "poc.quilr.ai/bff"
  AUTH_COOKIE: "quilr_web_auth"
  NEXT_PUBLIC_EXT_AUTH_COOKIE: "quilr_ext_auth"
  NEXT_PUBLIC_REFRESH_URL: "auth/auth/refresh"
  NEXT_PUBLIC_AUTH_COOKIE: "quilr_web_auth"
  NEXT_PUBLIC_EXT_AUTH_COOKIE: "quilr_ext_auth"
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
secretRef:
  name: auth-key-public
service:
  name: demo-quilr-web
  type: LoadBalancer
  port: 3000
  targetPort: 3000
