namespace: quilr
quilr:
  appname: event-transformation-service
configMap:
  KAFKA_TOPIC_READ: "eventsRaw"
  KAFKA_TOPIC_WRITE: "transformedOutput"
  KAFKA_GROUP_ID: "event-transformation"
  SERVICE_NAME: "event-transformation-service"
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: quilrdev.azurecr.io/event-transformation-service
  tag: latest_prod
  pullPolicy: Always
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
secretRef:
  name: auth-key-public
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
service:
  name: event-transformation-service
  type: ClusterIP
  port: 9073
  targetPort: 9073