namespace: quilr
quilr:
  appname: quilr-web
configMap:
  bffurl: "quilr.axisbank.com/bff"
  AUTH_COOKIE: "quilr_web_auth"
  NEXT_PUBLIC_EXT_AUTH_COOKIE: "quilr_ext_auth"
  NEXT_PUBLIC_REFRESH_URL: "auth/auth/refresh"
  NEXT_PUBLIC_AUTH_COOKIE: "quilr_web_auth"
  NEXT_PUBLIC_EXT_AUTH_COOKIE: "quilr_ext_auth"
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: quilrdev.azurecr.io/quilr-web
  tag: latest_iifl
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
secretRef:
  name: auth-key-public
secretName: azure-secret
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
service:
  name: quilr-web
  type: ClusterIP
  port: 3000
  targetPort: 3000
