namespace: quilr
quilr:
  appname: user-response-action-service
configMap:
  DATA_BASE_NAME: "in_memory_db"
  RELATIVE_PATH_TO_ACCESS_FOLDER: "response-action"
  BFF_URL: "https://quilr.axisbank.com/bff"
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: quilrdev.azurecr.io/user-response-action-service
  tag: latest_prod
  pullPolicy: Always
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
secretRef:
  name: auth-key-public
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
service:
  name: user-response-action-service
  type: ClusterIP
  port: 9085
  targetPort: 9085
# Additional fields
secretName: azure-secret
# azurefileshare:
#   name: user-response-action-service-spotnana-poc
secrets:
  vaultcapem: quilr-vault-capem
