namespace: quilr
quilr:
  appname: quilr-ai-services
  storagename: dlp-download-storage-prod-sentara
configMap: 
  SUPPORTED_EXTN_TYPES: "docx, pdf, txt, md"
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: quilrdev.azurecr.io/quilr-ai-services
  tag: latest_prod
  pullPolicy: Always
resources:
  requests:
    memory: "1024Mi"
    cpu: "125m"
  limits:
    memory: "2048Mi"
    cpu: "1000m"
secretRef:
  name: auth-key-public
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
service:
  name: quilr-ai-services
  type: ClusterIP
  port: 8050
  targetPort: 8050
# Additional fields
secretName: azure-secret
azurefileshare:
  name: secopsquilrstgfileshare
