apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.quilr.appname }}-configmap
  namespace: {{ .Values.namespace | default "quilr" }}  # Use namespace from values.yaml
data:
  BROWSER_EXT_URL: https://{{ .Values.configMap.bffurl }}/browser-extension
