# Namespace and application name
namespace: quilr
quilr:
  appname: quilr-migration-service

# CronJob-specific values
job:
  completions: "1"
  parallelism: "1"
  ttlSecondsAfterFinished: "86400"
  activeDeadlineSeconds: "86400"
  backoffLimit: "10"

# Vault configuration for annotations and passthrough
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  vault-env-passthrough: "VAULT_ADDR,VAULT_TOKEN"
  role: "default"
  path: "kubernetes"

# Container image configuration
image:
  repository: 975050335771.dkr.ecr.ap-south-1.amazonaws.com/main/quilr-migration-service
  tag: latest
  pullPolicy: Always

# resources:
#   requests:
#     memory: "512Mi"
#     cpu: "125m"
#   limits:
#     memory: "1024Mi"
#     cpu: "1000m"

# configMap:
