apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.quilr.appname }}-configmap
  namespace: {{ .Values.namespace | default "quilr" }}  # Use namespace from values.yaml
data:
  KAFKA_TOPIC_READ: {{ .Values.configMap.KAFKA_TOPIC_READ }}
  KAFKA_TOPIC_WRITE: {{ .Values.configMap.KAFKA_TOPIC_WRITE }}
  KAFKA_GROUP_ID: {{ .Values.configMap.KAFKA_GROUP_ID }}
  LOG_FILE: {{ .Values.configMap.LOG_FILE }}
  STATIC_DIR_LOCATION: {{ .Values.configMap.STATIC_DIR_LOCATION }}