namespace: quilr
quilr:
  appname: dlp-data-collector
  storagename: dlp-prompts-results
configMap:
  ENV: production
  DEBUG: "false"
  AGGREGATOR_URL: "http://dlp-data-aggregator:8092"
  BATCH_SIZE: "10"
  CHUNK_SIZE: "5"
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: 975050335771.dkr.ecr.us-east-1.amazonaws.com/main/dlp-data-collector
  tag: latest
  pullPolicy: Always
resources:
  requests:
    memory: "1024Mi"
    cpu: "125m"
  limits:
    memory: "2048Mi"
    cpu: "1000m"
secretRef:
  name: auth-key-public
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
service:
  name: dlp-data-collector
  type: ClusterIP
  port: 8093
  targetPort: 8093
# Additional fields
secretName: azure-secret
azurefileshare:
  name: dlp-prompts-results