apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.quilr.appname }}-configmap
  namespace: {{ .Values.namespace | default "quilr" }}  # Use namespace from values.yaml
data:
  KAFKA_BOOTSTRAP_SERVER: "{{ .Values.configMap.KAFKA_BOOTSTRAP_SERVER }}"
  KAFKA_TOPIC_READ: "{{ .Values.configMap.KAFKA_TOPIC_READ }}"
  KAFKA_TOPIC_WRITE: "{{ .Values.configMap.KAFKA_TOPIC_WRITE }}"
  KAFKA_GROUP_ID: "{{ .Values.configMap.KAFKA_GROUP_ID }}"
  CONTENT_SERVER_URL: "{{ .Values.configMap.CONTENT_SERVER_URL }}"
  SERVICE_NAME: "{{ .Values.configMap.SERVICE_NAME }}"
  SEARCH_API_ENDPOINT: "{{ .Values.configMap.SEARCH_API_ENDPOINT }}"
  APP_SYNC_API_ENDPOINT: "{{ .Values.configMap.APP_SYNC_API_ENDPOINT }}"
