apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.quilr.appname }}
  namespace: {{ .Values.namespace | default "quilr" }}  # Use namespace from values.yaml
  labels:
    app: {{ .Values.quilr.appname }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.quilr.appname }}
  ports:
    - name: {{ .Values.quilr.appname }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
