namespace: quilr
quilr:
  appname: quilr-auth-ts
configMap:
  # Database Configuration
  QUILR_DB_TYPE: "postgres"
  QUILR_DB_PORT: "5432"
  QUILR_DB_SSL: "true"
  # OAuth Configuration
  ACCESS_TOKEN_EXPIRES_IN_VAL: "4h"
  REFRESH_TOKEN_EXPIRES_IN_VAL: "1d"
  OAUTH_LOGIN_SCOPES: "openid email profile offline_access https://graph.microsoft.com/User.Read"
  OAUTH_FAILURE_URL: "/en/login"
  #OAUTH_SUCCESS_URL: 

  #OAUTH_SUCCESS_URL: 
  OAUTH_CALLBACK_URL: "/auth/auth/microsoft/callback"
  OAUTH_REFRESH_SCOPES: "openid profile offline_access https://graph.microsoft.com/email https://graph.microsoft.com/Mail.Read https://graph.microsoft.com/Directory.Read.All https://graph.microsoft.com/Application.Read.All https://graph.microsoft.com/Mail.Read.Shared https://graph.microsoft.com/Mail.ReadBasic https://graph.microsoft.com/User.Read.All https://graph.microsoft.com/User.ReadBasic.All https://graph.microsoft.com/AuditLog.Read.All https://graph.microsoft.com/Reports.Read.All"
  OAUTH_COMMON_TENANT_ID: "common"
  OAUTH_REFRESH_TOKEN_URL: "https://login.microsoftonline.com/common/oauth2/v2.0/token"
  QUILR_AUTH_COOKIE: "quilr_web_auth"
  # Application and Dashboard Configuration
  #DASHBOARD_URL: 

  # Vault Configuration
  VAULT_STORE_API: "/oauth/login/persist"
  VAULT_FETCH_API: "/oauth/login/retrieve"
  # Email Service Configuration
  #EMAIL_REDIRECT_URL: 
  EMAIL_SENDING_SERVICE_URL: "/email-service/api/v1/email/send"
  # Search Service Configuration
  SEARCH_SERVICE_URL: "/search/api/v1/search/"
  # Integration and Tracking Configuration
  OAUTH_ADMIN_CONSENT_URI: "/auth/auth/admin-landing"
  OAUTH_INTEGRATION_LIST_URL: "/instance-manager/integrations"
  OAUTH_INITIATE_FETCHING_URL: "/instance-manager/onboarding/initiate?integrationId"
  OAUTH_PERCENTAGE_TRACKING_URL: "/content-tracking/pipelines/track/integration/"
  # Static Content URLs
  # OAUTH_ACCESS_DENIED_HTML_URL: "https://staticcontent1.blob.core.windows.net/quilrstatic/OAuth/accessDenied.html"
  # OAUTH_WELCOME_EMAIL_HTML_URL: "https://staticcontent1.blob.core.windows.net/quilrstatic/OAuth/welcomeToQuilr.html"
  # OAUTH_ACCESS_REQUEST_HTML_URL: "https://staticcontent1.blob.core.windows.net/quilrstatic/OAuth/accessRequest.html"
  # OAUTH_ACCESS_GRANTED_HTML_URL: "https://staticcontent1.blob.core.windows.net/quilrstatic/OAuth/accessGranted.html"
  # OAUTH_INVITAION_EMAIL_HTML_URL: "https://staticcontent1.blob.core.windows.net/quilrstatic/OAuth/invitationEmail.html"
  # OAUTH_ANALYSIS_EMAIL_HTML_URL: "https://staticcontent1.blob.core.windows.net/quilrstatic/OAuth/analysisEmail.html"
  # OAUTH_TRIAL_EXPIRED_HTML_URL: "https://staticcontent1.blob.core.windows.net/quilrstatic/OAuth/trialExpiring.html"
  # WELCOME_EMAIL_URL: "https://staticcontent1.blob.core.windows.net/quilrstatic/OAuth/welcome_email.html"
  OAUTH_ACCESS_DENIED_HTML_URL: "http://quilr-static-content:8080/quilrstatic/OAuth/accessDenied.html"
  OAUTH_WELCOME_EMAIL_HTML_URL: "http://quilr-static-content:8080/quilrstatic/OAuth/welcomeToQuilr.html"
  OAUTH_ACCESS_REQUEST_HTML_URL: "http://quilr-static-content:8080/quilrstatic/OAuth/accessRequest.html"
  OAUTH_ACCESS_GRANTED_HTML_URL: "http://quilr-static-content:8080/quilrstatic/OAuth/accessGranted.html"
  OAUTH_INVITAION_EMAIL_HTML_URL: "http://quilr-static-content:8080/quilrstatic/OAuth/invitationEmail.html"
  OAUTH_ANALYSIS_EMAIL_HTML_URL: "http://quilr-static-content:8080/quilrstatic/OAuth/analysisEmail.html"
  OAUTH_TRIAL_EXPIRED_HTML_URL: "http://quilr-static-content:8080/quilrstatic/OAuth/trialExpiring.html"
  WELCOME_EMAIL_URL: "http://quilr-static-content:8080/quilrstatic/OAuth/welcome_email.html"
  # Integration Redirect URLs
  OAUTH_INTEGRATION_REDIRECT_URL: "/en/integration/oauth/redirect"
  OAUTH_INTEGRATION_FAILURE_URL: "/en/integration/ba77ae93-c3d1-4db3-ac68-70de7ade2e71"
  INTEGRATIONS_REDIRECT_URI: "/auth/auth/integration-admin-landing/microsoft"
  # OAuth Google Configuration
  OAUTH_GOOGLE_CALLBACK_URL: "/auth/auth/google/callback"
  GOOGLE_LOGIN_SCOPES: "profile openid email"
  OAUTH_GOOGLE_FAILURE_URL: "/en/oauth"
  # Miscellaneous
  SCHEMA_REGISTRY_URL: "http://schema-registry-service:8096/db/connection/onboard"
  APPLICATION_URL: "https://graph.microsoft.com/v1.0/applications"
  OAUTH_USER_ROLE_API: "https://graph.microsoft.com/v1.0/me/memberOf"
  OAUTH_JUSTME_SCOPES: "openid profile email offline_access https://graph.microsoft.com/User.Read"
  weburl: "quilr.axisbank.com"
  bffurl: "quilr.axisbank.com/bff"
  BROWSER_EXT_SUCCESS_URI: "https://quilr.axisbank.com/ext-beoauth/loading"
  OAUTH_BROWSER_EXT_FAILURE_URL: "https://quilr.axisbank.com/ext-beoauth/error"
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: quilrdev.azurecr.io/quilr-auth-ts
  tag: latest_prod
  pullPolicy: Always
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
secretRef:
  name: auth-keys
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
service:
  name: quilr-auth-ts
  type: ClusterIP
  port: 5555
  targetPort: 5555
