## values.yaml
#****************** for deployment.yaml ******************#
namespace: quilr
quilr:
  appname: data-fabric-core-service
### for hpa.yaml

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: 975050335771.dkr.ecr.us-east-1.amazonaws.com/quilr-preprod/data-fabric-core-service
  tag: latest
  pullPolicy: Always
configMap:
  STATIC_DIR_LOCATION: "/data-fabric-core-service"
secretRef:
  name: auth-key-public
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
secretName: azure-secret
azurefileshare:
  servicefileshare:
    name: data-fabric-core-service # Replace with the name of your service file share
  truststorefileshare:
    name: truststore-cloud-saas-env # Replace with the name of your truststore file share
    #################################################    device-transformation-service:   ###########################################################################################
secrets:
  vaulttrustrore: quilr-vault-trustore
  #################################################    device-transformation-service:   ###########################################################################################
#****************** for service.yaml ******************#

service:
  name: data-fabric-core-service
  type: ClusterIP
  port: 9031
  targetPort: 9031
#****************** for configmap.yaml - particularly service related ******************#
#configMap:
# VAULT_CERT_FILE: 'file:/data-fabric-core-service-truststore/truststore.jks'
#commented configmap.yaml which is service specific
