## No specific configmap.yaml for the service
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Values.quilr.appname }}-configmap
  namespace: {{ .Values.namespace | default "default" }}  # Use namespace from values.yaml
data:
  RELAY_CONFIG_DIR: "{{ .Values.configMap.RELAY_CONFIG_DIR }}"
  EDM_SERVER_DATA_DIR: "{{ .Values.configMap.EDM_SERVER_DATA_DIR }}"
  EMBEDDING_MODEL_URL: "{{ .Values.configMap.EMBEDDING_MODEL_URL }}"
  STAGE2_URL: "{{ .Values.configMap.STAGE2_URL }}"