apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.quilr.appname }}-configmap
  namespace: {{ .Values.namespace | default "quilr" }}  # Use namespace from values.yaml
data:
  logging_level: "{{ .Values.configMap.logging_level }}"
  VERBOSE: "{{ .Values.configMap.VERBOSE }}"
  DLP_API_URL: "{{ .Values.configMap.DLP_API_URL }}"
  FILE_PARSER_URL: "{{ .Values.configMap.FILE_PARSER_URL }}"
  EDM_SERVER_URL: "{{ .Values.configMap.EDM_SERVER_URL }}"