apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.quilr.appname }}-configmap
  namespace: {{ .Values.namespace | default "quilr" }}  # Use namespace from values.yaml
data:
  logging_level: "{{ .Values.configMap.logging_level }}"
  VERBOSE: "{{ .Values.configMap.VERBOSE }}"