apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.quilr.appname }}
  namespace: {{ .Values.namespace | default "quilr" }}  # Use namespace from values.yaml
  labels:
    app: {{ .Values.quilr.appname }}
spec:
  replicas: {{ .Values.hpa.minReplicas }}  # This will be managed by the HPA
  selector:
    matchLabels:
      app: {{ .Values.quilr.appname }}
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "{{ .Values.vault.addr }}"
        vault.security.banzaicloud.io/vault-role: "{{ .Values.vault.role }}"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/vault-agent: "false"
        vault.security.banzaicloud.io/vault-path: "{{ .Values.vault.path }}"
      name: {{ .Values.quilr.appname }}
      labels:
        app: {{ .Values.quilr.appname }}
    spec:
      containers:
        - name: {{ .Values.quilr.appname }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          # readinessProbe:
          #   tcpSocket:
          #     port: {{ .Values.service.port }}
          #   initialDelaySeconds: 90
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          #   failureThreshold: 5
          # livenessProbe:
          #   tcpSocket:
          #     port: {{ .Values.service.port }}
          #   initialDelaySeconds: 90
          #   periodSeconds: 5
          #   failureThreshold: 5  
          env:
            - name: DB_PASSWORD
              value: vault:secret/data/quilr-common-config-vault#DB_PASSWORD
            - name: DB_USERNAME
              value: vault:secret/data/quilr-common-config-vault#DB_USERNAME
            - name: DB_URL
              value: vault:secret/data/quilr-common-config-vault#DB_URL
            # - name: REDIS_HOST
            #   value: vault:secret/data/quilr-common-config-vault#REDIS_HOST
            - name: REDIS_PASSWORD
              value: vault:secret/data/quilr-common-config-vault#REDIS_PASSWORD
            - name: QUILR_GOOGLE_CONNECTOR_APP_NAME
              value: vault:secret/data/quilr-common-config-vault#QUILR_GOOGLE_CONNECTOR_APP_NAME
            - name: OAUTH_GOOGLE_CLIENT_SECRET
              value: vault:secret/data/quilr-common-config-vault#OAUTH_GOOGLE_CLIENT_SECRET
            - name: OAUTH_GOOGLE_CLIENT_ID
              value: vault:secret/data/quilr-common-config-vault#OAUTH_GOOGLE_CLIENT_ID
            - name: QUILR_GOOGLE_INTEGRATION_ID
              value: vault:secret/data/quilr-common-config-vault#QUILR_GOOGLE_INTEGRATION_ID
            - name: VAULT_API_TOKEN
              value: vault:secret/data/quilr-common-config-vault#VAULT_API_TOKEN
            - name: VAULT_TRUSTSTORE_PASSPHRASE
              value: vault:secret/data/quilr-common-config-vault#VAULT_TRUSTSTORE_PASSPHRASE  
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx1024m"
          envFrom:
            # - configMapRef:
            #     name: quilr-common-config
            - configMapRef:
                name: dlp-common-config
            - secretRef:
                name: {{ .Values.secretRef.name }}
            - configMapRef:
                name: {{ .Values.quilr.appname }}-configmap
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          volumeMounts:
            - name: efs-vol
              mountPath: /{{ .Values.quilr.storagename }}
              subPath: {{ .Values.azurefileshare.name }}
            - name: vault-truststore-volume
              mountPath: /{{ .Values.quilr.appname }}-truststore
              readOnly: true
      volumes:
        - name: efs-vol
          persistentVolumeClaim:
            claimName: efs-shared-pvc
        - name: vault-truststore-volume
          secret:
            secretName: {{ .Values.secrets.vaulttruststore }}
