namespace: quilr
quilr:
  appname: quilr-query-builder
  commonfileshare: quilr-data-upload
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
image:
  repository: quilrdev.azurecr.io/quilr-query-builder
  tag: latest_prod
  pullPolicy: IfNotPresent
configMap:
  AI_AXIS_PORT: '8052'
  GRAPH_NAME: 'neo4j'
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "2048Mi"
    cpu: "1000m"
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
secretRef:
  name: auth-key-public
service:
  name: quilr-query-builder
  type: ClusterIP
  port: 8052
  targetPort: 8052
secretName: azure-secret
azurefileshare:
  name: secopsquilrstgfileshare
