namespace: quilr
quilr:
  appname: axis-analytics-job
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
image:
  repository: 975050335771.dkr.ecr.ap-south-1.amazonaws.com/main/axis-analytics-job
  tag: latest
  pullPolicy: Always
configMap:
  AI_AXIS_PORT: '8051'
  GRAPH_NAME: 'neo4j'
resources:
  requests:
    memory: "1024Mi"
    cpu: "250m"
  limits:
    memory: "2048Mi"
    cpu: "1000m"
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
secretRef:
  name: auth-key-public
service:
  name: axis-analytics-job
  type: ClusterIP
  port: 8051
  targetPort: 8051
