namespace: quilr
quilr:
  appname: quilr-okta-fabric
configMap:
  KAFKA_TOPIC_USER: "usersRaw"
  KAFKA_TOPIC_APP: "appsRaw"
  logging_level: "DEBUG"
  FetchInterval: "300"
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  vault-env-passthrough: "VAULT_ADDR,VAULT_TOKEN"
  role: "default"
  path: "kubernetes"
image:
  repository: 975050335771.dkr.ecr.us-east-1.amazonaws.com/main/quilr-okta-fabric
  tag: latest
  pullPolicy: Always
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
secretRef:
  name: auth-key-public
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
service:
  name: quilr-okta-fabric
  type: ClusterIP
  port: 8036
  targetPort: 8036
