apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.quilr.appname }}
  namespace: {{ .Values.namespace | default "quilr" }}  # Use namespace from values.yaml
  labels:
    app: {{ .Values.quilr.appname }}
spec:
  replicas: {{ .Values.hpa.minReplicas }}  # This will be managed by the HPA
  selector:
    matchLabels:
      app: {{ .Values.quilr.appname }}
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "{{ .Values.vault.addr }}"
        vault.security.banzaicloud.io/vault-env-passthrough: "VAULT_ADDR,VAULT_TOKEN"
        vault.security.banzaicloud.io/vault-role: "{{ .Values.vault.role }}"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/vault-agent: "true"
        vault.security.banzaicloud.io/vault-path: "{{ .Values.vault.path }}"
      name: {{ .Values.quilr.appname }}
      labels:
        app: {{ .Values.quilr.appname }}
    spec:
      containers:
        - name: {{ .Values.quilr.appname }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5  
          env:
            - name: PG_PASSWORD
              value: vault:secret/data/quilr-common-config-vault#PG_PASSWORD
            - name: PG_USER
              value: vault:secret/data/quilr-common-config-vault#PG_USER
            - name: PG_HOST
              value: vault:secret/data/quilr-common-config-vault#PG_HOST
            - name: VAULT_TOKEN
              value: vault:secret/data/quilr-common-config-vault#VAULT_TOKEN
            - name: REDIS_PASSWORD
              value: vault:secret/data/quilr-common-config-vault#REDIS_PASSWORD
            - name: ADMIN_QUILLY_APPID
              value: vault:secret/data/quilr-common-config-vault#ADMIN_QUILLY_APPID
            - name: ADMIN_QUILLY_APPSECRET
              value: vault:secret/data/quilr-common-config-vault#ADMIN_QUILLY_APPSECRET  
          envFrom:
            - configMapRef:
                name: quilr-common-config
            - secretRef:
                name: {{ .Values.secretRef.name }}
            - configMapRef:
                name: {{ .Values.quilr.appname }}-configmap
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
      volumes:
        - name: agent-secrets
          emptyDir: {}
