namespace: quilr
quilr:
  appname: quilr-dlp-prompt-category
configMap:
  STAGE2_URL: "http://quilr-dlp-stage2:23333"
  PROMPT_CATEGORY_BASE_URL: "http://quilr-dlp-prompt-category-base:8080"
### for hpa.yaml
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
image:
  repository: 975050335771.dkr.ecr.ap-south-1.amazonaws.com/main/quilr-dlp-prompt-category
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: quilr-dlp-prompt-category
  type: ClusterIP
  port: 8000
  targetPort: 8000
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
secretRef:
  name: auth-key-public
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"

