# Namespace and application name
namespace: quilr
quilr:
  appname: quilr-housekeeping-script

# CronJob-specific values
cronjob:
  schedule: "0 */1 * * *"
  concurrencyPolicy: "Forbid"
  ttlSecondsAfterFinished: 300

# Vault configuration for annotations and passthrough
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"

# Container image configuration
image:
  repository: 975050335771.dkr.ecr.us-east-1.amazonaws.com/quilr-preprod/quilr-housekeeping-script
  tag: latest
  pullPolicy: Always
