#****************** for deployment.yaml ******************#
namespace: quilr
quilr:
  appname: quilr-ai-config-manager
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85

vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"

image:
  repository: 975050335771.dkr.ecr.ap-south-1.amazonaws.com/main/quilr-ai-config-manager
  tag: latest
  pullPolicy: Always

configMap:
  logging_level: "INFO"
  VERBOSE: "true"
  DLP_API_URL: "http://quilr-dlp-server:8000"
  FILE_PARSER_URL: "http://quilr-dlp-fileparsing:9001"
  EDM_SERVER_URL:  "http://quilr-dlp-edm:3455"

secretRef:
  name: auth-key-public

resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "2Gi"
    cpu: "1000m"
#****************** for service.yaml ******************#
service:
  name: quilr-ai-config-manager
  type: ClusterIP
  port: 8000
  targetPort: 8000
#*******************************************************#
