# clickhouse-values.yaml

shards: 1
replicaCount: 1

resourcesPreset: medium

auth:
  username: quilradmin
  password: "QU1lr$F345#we"

keeper:
  enabled: false

externalZookeeper:
  servers:
    - zookeeper-server
  port: 2181

# Mount the init scripts ConfigMap
extraVolumes:
  - name: quilr-clickhouse-initdb-scripts
    configMap:
      name: quilr-clickhouse-initdb-scripts
  - name: quilr-clickhouse-initdb-scripts-devops-378
    configMap:
      name: quilr-clickhouse-initdb-scripts-devops-378


extraVolumeMounts:
  - name: quilr-clickhouse-initdb-scripts
    mountPath: /docker-entrypoint-initdb.d
  - name: quilr-clickhouse-initdb-scripts-devops-378
    mountPath: /quilr-devops-378

image:
  registry: quilrdev.azurecr.io
  repository: tp/clickhouse
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: acr-secret

global:
  security:
    allowInsecureImages: true
