namespace: quilr
quilr:
  appname: content-alert-classification
configMap: {}
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: quilrdev.azurecr.io/content-alert-classification
  tag: latest_prod
  pullPolicy: Always
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
secretRef:
  name: auth-key-public
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
service:
  name: content-alert-classification
  type: ClusterIP
  port: 8080
  targetPort: 8080
