#****************** for deployment.yaml ******************#
namespace: quilr
quilr:
  appname: quilr-siem-service

### for hpa.yaml
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85

vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"

image:
  repository: quilrdev.azurecr.io/quilr-siem-service
  tag: latest_prod
  pullPolicy: Always

configMap:
  logging_level: "INFO"

secretRef:
  name: auth-key-public

resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"


service:
  name: quilr-siem-service
  type: ClusterIP
  port: 8000
  targetPort: 8000

