version: 1.0.4
criticality: 4
mode: monitor
control_name: User is trying to upload sensitive data
control_description: ""
posture:
  id: PID_06
behavior:
  id: BID_203
use_case:
  id: UC043
schedule: "@every 10m"
trigger_conditions:
  - operator: null
    filter_group: null
    filter_condition:
      attribute_type: ATTR_Browser_001
      attribute_id: BROWSER-002
      condition: is_equal_to
      value: upload
      graph_property: null
      extension_property: null
  - operator: AND
    filter_group: null
    filter_condition:
      attribute_type: ATTR_DATA_001
      attribute_id: DATA-009
      condition: is_equal_to
      value: "true"
      graph_property: null
      extension_property: null
actions: []
is_active: true
is_internal: false
