version: 1.0.0
criticality: 4
mode: monitor
control_name: Discovering New AI App
control_description: "This control monitors the introduction of new AI applications within the organization."
posture:
  id: PID_01
behavior:
  id: BID_17
use_case:
  id: UC001
trigger_conditions:
- operator: null
  filter_group: null
  filter_condition:
    value: visit
    condition: is_equal_to
    attribute_id: BROWSER-002
    attribute_type: ATTR_Browser_001
- operator: AND
  filter_group: null
  filter_condition:
    value: generative ai
    condition: is_equal_to
    attribute_id: APP-001
    attribute_type: ATTR_APP_001
- operator: AND
  filter_group: null
  filter_condition:
    value: "true"
    condition: is_equal_to
    attribute_id: APP-013
    attribute_type: ATTR_APP_001
actions:
- type:
    id: ACTP_02
  name:
    id: ACT_308
  description: 
  meta:
    channel: browser
    engagement_type: templatized
    message_template: justify-using-a-new-ai-app
    execution_type: tool
    execution_module: send_templated_user_message
    browser_action: Ask
    prompt_frequency: 
    default_conversation_params:
      is_urgent: false
      tone: 
      cc_manager: false
      sla: 
      sla_duration_unit: 
      reminder_count: 
      custom_message: 
    custom_conversation_params: