version: 1.0.0
control_name: Logging into SaaS applications using compromised passwords
criticality: 3
control_description: This control applies when users log into applications using
  compromised passwords. The base criteria applied are of password strength,
  sign-up activity, and criticality being not set. No additional criteria are
  considered for this control.
mode: monitor
use_case:
  id: UC007
behavior:
  id: BID_08
posture:
  id: PID_03
trigger_conditions:
  - operator: null
    filter_group: null
    filter_condition:
      value: "true"
      condition: is_equal_to
      attribute_id: ACC-004
      attribute_type: ATTR_ACC_001
      extension_property: check.isPasswordCompromised
  - operator: AND
    filter_group: null
    filter_condition:
      value: "false"
      condition: is_equal_to
      attribute_id: BROWSER-001
      attribute_type: ATTR_Browser_001
      extension_property: checkOb.check.properties.signup
actions:
  - type:
      id: ACTP_02
    name:
      id: ACT_44
    meta:
      custom_conversation_params:
        is_urgent: false
        tone: null
        cc_manager: false
        sla: null
        sla_duration_unit: null
        reminder_count: null
        custom_message: null
      message_template: null
    outcomes: []
