version: 1.0.0
control_name: Logging into SaaS applications reusing passwords of another application
criticality: 4
control_description: This control applies when users log into applications
  reusing the passwords of another application. The base criteria applied is
  that the activity must be application logins. Additional criterion considered
  is that the credentials reused belong to any application in general.
mode: monitor
use_case:
  id: UC010
behavior:
  id: BID_10
posture:
  id: PID_03
trigger_conditions: []
actions: []
is_internal: true
