version: 1.0.0
control_name: Logging into IDP/SSO applications using weak passwords
criticality: 5
control_description: This control applies when users log into IDP/SSO
  applications using weak passwords. The base criteria applied are of password
  strength and login activity. Additional criterion considered is that the
  application must be an IDP or an SSO application.
mode: monitor
use_case:
  id: UC011
behavior:
  id: BID_11
posture:
  id: PID_03
trigger_conditions:
  - operator: null
    filter_group: null
    filter_condition:
      value: "2"
      condition: is_less_than_equal_to
      attribute_id: ACC-003
      attribute_type: ATTR_ACC_001
      extension_property: checkOb.check.properties.password_strength
  - operator: AND
    filter_group: null
    filter_condition:
      value: "false"
      condition: is_equal_to
      attribute_id: BROWSER-001
      attribute_type: ATTR_Browser_001
      extension_property: checkOb.check.properties.signup
  - operator: AND
    filter_group: null
    filter_condition:
      value: "true"
      condition: is_equal_to
      attribute_id: APP-018
      attribute_type: ATTR_APP_001
      extension_property: isIdp
actions:
  - type:
      id: ACTP_02
    name:
      id: ACT_45
    meta:
      custom_conversation_params:
        is_urgent: false
        tone: null
        cc_manager: false
        sla: null
        sla_duration_unit: null
        reminder_count: null
        custom_message: null
      message_template: null
    outcomes: []
