version: 1.0.0
criticality: 5
mode: monitor
control_name: Reusing a critical application password for other applications
control_description: This control monitors and prevents the reuse of critical application passwords for other applications to ensure password hygiene and security.
posture:
  id: PID_03
behavior:
  id: BID_10
use_case:
  id: UC013
trigger_conditions:
- operator: 
  filter_condition:
    attribute_type: ATTR_Browser_001
    attribute_id: BROWSER-001
    extension_property: checkOb.check.properties.signup
    condition: is_in
    value:
    - "false"
    - "true"
  filter_group: 
- operator: AND
  filter_condition:
    attribute_type: ATTR_RPA_001
    attribute_id: RPA-003
    extension_property: check.reusedPassword.$.isCritical
    condition: is_equal_to
    value: Critical
  filter_group: 
actions: []
 
