version: 1.0.0
control_name: Logging  into SaaS applications using credentials of another admin user
criticality: 5
control_description: "This control applies when users log into applications
  using credentials of admin users. The base criteria applied is that the
  activity must be application logins. Additional criterion is that the
  credentials used belong to admin users. In other words, the account owner of
  the app is in the admins group. "
mode: monitor
use_case:
  id: UC008
behavior:
  id: BID_09
posture:
  id: PID_03
trigger_conditions:
  - operator: null
    filter_group: null
    filter_condition:
      value: "false"
      condition: is_equal_to
      attribute_id: BROWSER-001
      attribute_type: ATTR_Browser_001
      extension_property: checkOb.check.properties.signup
  - operator: AND
    filter_group: null
    filter_condition:
      value:
        - Admins
      condition: is_in
      attribute_id: ACOW-002
      attribute_type: ATTR_ACOW_001
      extension_property: check.userDetails.groups
actions:
  - type:
      id: ACTP_02
    name:
      id: ACT_39
    meta:
      custom_conversation_params:
        is_urgent: false
        tone: null
        cc_manager: false
        sla: null
        sla_duration_unit: null
        reminder_count: null
        custom_message: null
      message_template: null
    outcomes: []
