version: 1.0.0
control_name: Signing up for critical SaaS applications using compromised passwords
criticality: 5
control_description: This control applies when users sign up for critical
  applications using compromised passwords. The base criteria applied are of
  password strength and sign up activity. Additional criterion considered is
  that of application criticality.
mode: monitor
use_case:
  id: UC007
behavior:
  id: BID_08
posture:
  id: PID_03
trigger_conditions:
  - operator: null
    filter_group: null
    filter_condition:
      value: "true"
      condition: is_equal_to
      attribute_id: ACC-004
      attribute_type: ATTR_ACC_001
      extension_property: check.isPasswordCompromised
  - operator: AND
    filter_group: null
    filter_condition:
      value: "true"
      condition: is_equal_to
      attribute_id: BROWSER-001
      attribute_type: ATTR_Browser_001
      extension_property: checkOb.check.properties.signup
  - operator: AND
    filter_group: null
    filter_condition:
      value: Critical
      condition: is_equal_to
      attribute_id: APP-003
      attribute_type: ATTR_APP_001
      extension_property: has_app_settings.criticality
actions:
  - type:
      id: ACTP_02
    name:
      id: ACT_47
    meta:
      custom_conversation_params:
        is_urgent: false
        tone: null
        cc_manager: false
        sla: null
        sla_duration_unit: null
        reminder_count: null
        custom_message: null
      message_template: null
    outcomes: []
