apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.quilr.appname }}-configmap
  namespace: {{ .Values.namespace | default "quilr" }}  # Use namespace from values.yaml
data:
  logging_level: "{{ .Values.configMap.logging_level }}"
  VERBOSE: "{{ .Values.configMap.VERBOSE }}"
  inference_model: "{{ .Values.configMap.inference_model }}"
  instruction_model: "{{ .Values.configMap.instruction_model }}"
  neo4j.rag: "{{ .Values.configMap.neo4j_rag }}"
  neo4jrag.enable: "{{ .Values.configMap.neo4jrag_enable }}"
  DOCSTORE: "{{ .Values.configMap.DOCSTORE }}"
  rag_model: "{{ .Values.configMap.rag_model }}"
  instructionfile: "{{ .Values.configMap.instructionfile }}"
  TOKENIZERS_PARALLELISM: "{{ .Values.configMap.TOKENIZERS_PARALLELISM }}"
  guardrails.enable: "{{ .Values.configMap.guardrails_enable }}"
  guardrails: "{{ .Values.configMap.guardrails }}"
