id: 492ad121-edf3-4be5-ae95-56c793df1d02
version: 1.3
code: ACT_55
name: Block signup/Login for reuse of IDP password
type: action
actiontype: ACTP_02
config:
  meta:
    channel: null
    engagement_type: templatized
    message_template: block-signup-login-for-reuse-of-idp-critical-application-password
    execution_type: tool
    execution_module: send_templated_user_message
    browser_action: Block
    blocked: false
tags:
  - UC010
behavior:
  - BID_10
createdon: 1745385288304 
updatedon: 1758018676721
