code: ACT_237
createdon: 1710504494000
id: 7b83b73b-99ac-4c3f-9fee-2f8aa6b1ce3b
version: 1.2
actiontype: ACTP_02
behavior:
- BID_22
updatedon: 1758018676721
name: Block SaaS application by organisation
type: action
tags:
- UC039
config:
  meta:
    execution_type: tool
    browser_action: Block
    blocked: true
    engagement_type: templatized
    execution_module: send_templated_user_message
    message_template: block-application-by-organisation
    channel: 

