id: 0ae940f7-3605-4cf4-9556-b97815c6c7f1
version: 1.4
code: ACT_56
name: Block signup/Login for reuse of Critical password
type: action
actiontype: ACTP_02
config:
  meta:
    channel: null
    engagement_type: templatized
    message_template: block-signup-login-for-reuse-of-idp-critical-application-password
    execution_type: tool
    execution_module: send_templated_user_message
    browser_action: Block
    blocked: false
tags:
  - UC013
behavior:
  - BID_10
createdon: 1745385288304 
updatedon: 1758018676721
