namespace: quilr
quilr:
  appname: alert-transformation-service
configMap:
  KAFKA_TOPIC_READ: "alertsRaw"
  KAFKA_TOPIC_WRITE: "transformedOutput"
  KAFKA_GROUP_ID: "alert-transformation"
  SERVICE_NAME: "alert-transformation-service"
  PROMPT_FILE_URL: "http://content-server-transformations:8001/transformation?filepath=alerts/microsoft/prompt.yml"
  LLM_SERVICE_URL: "http://quilr-llm-service:9074/azure/synchronous/chat/completion"
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: 975050335771.dkr.ecr.ap-south-1.amazonaws.com/main/alert-transformation-service
  tag: latest
  pullPolicy: Always
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
secretRef:
  name: auth-key-public
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
service:
  name: alert-transformation-service
  type: ClusterIP
  port: 9075
  targetPort: 9075