#****************** for deployment.yaml ******************#
namespace: quilr
quilr:
  appname: quilr-eam-service

### for hpa.yaml
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85

vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"

image:
  repository: 975050335771.dkr.ecr.ap-south-1.amazonaws.com/main/quilr-eam-service
  tag: latest
  pullPolicy: Always

configMap:
  PRIVATE_KEY: '/app/data/private.key'
  PUBLIC_KEY: '/app/data/public.pem'
  JWKS_FILE: '/app/data/jwks.json'

secretRef:
  name: auth-key-public

resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"

#****************** for service.yaml ******************#
service:
  name: quilr-eam-service
  type: ClusterIP
  port: 8000
  targetPort: 8000
#*******************************************************#
