namespace: quilr
quilr:
  appname: device-transformation-service
configMap:
  KAFKA_BOOTSTRAP_SERVER: "kafka-server:9092"
  KAFKA_TOPIC_READ: "deviceRaw"
  KAFKA_TOPIC_WRITE: "transformedOutput"
  KAFKA_GROUP_ID: "device-transformation-service"
  CONTENT_SERVER_URL: "http://content-server-transformations:8001"
  SERVICE_NAME: "device-transformation-service"
  SEARCH_API_ENDPOINT: "http://search-service:8002"
  APP_SYNC_API_ENDPOINT: "http://app-sync-client-service:8081"
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  role: "default"
  path: "kubernetes"
image:
  repository: quilrdev.azurecr.io/device-transformation-service
  tag: latest_prod
  pullPolicy: Always
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"
secretRef:
  name: auth-key-public
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
service:
  name: device-transformation-service
  type: ClusterIP
  port: 9030
  targetPort: 9030