namespace: quilr
quilr:
  appname: quilr-agent-service
  storagename: dlp-download-storage-preprod
configMap:
  logging_level: "INFO"
  VERBOSE: "true"
  inference_model: "gpt-4.1-nano"
  instruction_model: "gpt-4.1-mini"
  neo4j.rag: langchain
  neo4jrag.enable: "true"
  DOCSTORE: "/app/docs"
  rag_model: "gpt-4.1-nano"
  guardrails: "/app/config"
  TOKENIZERS_PARALLELISM: "false"
  guardrails_enable: "true"
  instructionfile: "/app/library/IntructionSet.txt"
vault:
  addr: "https://vault.quilr.svc.cluster.local:8200"
  vault-env-passthrough: "VAULT_ADDR,VAULT_TOKEN"
  role: "default"
  path: "kubernetes"
image:
  repository: 975050335771.dkr.ecr.ap-south-1.amazonaws.com/main/quilr-agent-service
  tag: latest
  pullPolicy: Always
resources:
  requests:
    memory: "512Mi"
    cpu: "125m"
  limits:
    memory: "2Gi"
    cpu: "1000m"
secretRef:
  name: auth-key-public
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85
service:
  name: quilr-agent-service
  type: ClusterIP
  port: 8000
  targetPort: 8000
# Additional Fields
azurefileshare:
  name: dlp-download-storage-preprod
